### ISSUE TITLE
Webpack Watcher crashes when editing a file since last version

### ISSUE THREAD

**Issue by guyromb** [webpack/enhanced-resolve#105]
Version 3.4.0. The issues was not there in 3.3.0.
The following errors happens (+ stops the npm process), after saving a file, and the watcher refreshes.

`node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:145
                       if(key.startsWith(what))
                             ^

TypeError: Cannot read property 'startsWith' of undefined`

**Comment by sokra** [comment]
fixed in 3.4.1

**Comment by guyromb** [comment]
thank you @sokra . will test it
