### ISSUE TITLE
3.4.0 breaks Angular CLI

### ISSUE THREAD

**Issue by filipesilva** [webpack/enhanced-resolve#107]
Hi there,

It seems the recent `3.4.0` breaks `@ngtools/webpack`, which is at the core `@angular/cli` (https://github.com/angular/angular-cli/issues/7113).

In the https://github.com/webpack/enhanced-resolve/releases/tag/v3.4.0 release I only see performance changes so am not too sure what changed that breaks our stuff.

Our direct usage of `enhanced-resolve` is contained in https://github.com/angular/angular-cli/blob/master/packages/@ngtools/webpack/src/paths-plugin.ts.

Is there anything that comes to mind we need to change to support `^3.4.0`?

Thanks for your time.

**Comment by Tragetaschen** [comment]
#98 ...

**Comment by filipesilva** [comment]
Right you are, closing in favor of that one and moving my comment there.
