### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Jetsly** [webpack/enhanced-resolve#108]
._enhanced-resolve@3.4.0@enhanced-resolve/lib/CachedInputFileSystem.js:146
                        if(key.startsWith(what))

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge

**Comment by Joachricar** [comment]
This issue has been resolved here: https://github.com/webpack/enhanced-resolve/issues/97
TL;DR upgrade to 3.4.1
