### ISSUE TITLE
Concord modules?

### ISSUE THREAD

**Issue by gdborton** [webpack/enhanced-resolve#112]
We've got a rather large build, and after grep'ing through our codebase, it seems that none of our dependencies are using the concord field in package.json. Is this something that is still being pursued or could it be removed from `enhanced-resolve`?

**Comment by ljharb** [comment]
Or at the very least, controllable by an option? I don't know who even uses "concord modules", but it doesn't seem like it's anywhere near the majority.

**Comment by sokra** [comment]
It's now controllable by option and off by default.
