### ISSUE TITLE
bower component main field can be array

### ISSUE THREAD

**Issue by joscha** [webpack/enhanced-resolve#12]
I bower, the `main` field in `bower.json` can be an array, e.g.: https://github.com/rstacruz/nprogress/blob/master/bower.json#L12 - would you merge a PR for that? Currently as a workaround you have to set `alias`es within the `webpack.config.js` for those libraries.

**Comment by sokra** [comment]
This can be handled in enhanced-resolve. Check https://github.com/lpiepiora/bower-webpack-plugin

**Comment by joscha** [comment]
@sokra I'll give it a try.

**Comment by linaspasv** [comment]
I have made a small plugin to support array like ``main`` fields in ``bower.json``: https://github.com/codewizz/bower-resolve-webpack-plugin
