### ISSUE TITLE
How to write a plugin to filter a resolution?

### ISSUE THREAD

**Issue by mhelvens** [webpack/enhanced-resolve#122]
I need to write a resolver plugin that runs at the last moment (after a reference was resolved to an existing file). Based on some condition (to do with the relative positions of `request.path` and `request.context.issuer`), should then either error out or let that resolution pass through normally.

But I can't figure out where to hook into the pipeline. From what I can tell, if I do `resolver.plugin('existing-file')`, the plugin never runs, even though the callback stack tells me it did go through that phase. After reading through the code, I found out I could prepend `after-` to any phase, but `after-existing-file` never runs either. Some help would be appreciated.

**Comment by evilebottnawi** [comment]
Sorry for delay, close in favor https://github.com/webpack/enhanced-resolve/issues/119#issuecomment-634154422
