### ISSUE TITLE
DeprecationWarnings are vague and don't refer to enhanced-resolve

### ISSUE THREAD

**Issue by mzgoddard** [webpack/enhanced-resolve#125]
The DeprecationWarnings

https://github.com/webpack/enhanced-resolve/blob/9c43df0768ca47b409cc238cb99712f9cb664156/lib/Resolver.js#L31-L41

are vague and don't refer to enhanced-resolve, or the Resolver or the methods they are found in. Simple additions, like in [tapable/lib/Tapable.js](https://github.com/webpack/tapable/blob/512c3a1b4174d7e6c1e22d7c7dec5c77ca5bcdbf/lib/Tapable.js#L67), referring to any of these would help a lot.

**Comment by sokra** [comment]
Send a PR.

In general you get a stack trace for deprecations with `--trace-deprecation` for node.js
