### ISSUE TITLE
README (Documentation)

### ISSUE THREAD

**Issue by skipjack** [webpack/enhanced-resolve#133]
> In regards to webpack/webpack.js.org#1754 and [this comment](https://github.com/webpack/webpack.js.org/pull/1754#issuecomment-353922118).

The documentation on the `next` branch of webpack.js.org now points to this package and it's README more prominently from the `resolvers.md` page. It seems the README for this package is totally out of date with the current code (though I could be wrong). I think the following needs to be documented:

- Each available hook (preferably using the same format we use here)
  - Type of underlying `tapable` hook
  - Brief description and optionally a small example
  - Any parameters passed
- A description of each available class method and their parameters (e.g. `doResolve`)

@mlcohen, seeing as you dug into this a bit in webpack/webpack.js.org#1458, would you be willing to help out with updating this README? You may want to collaborate with @sokra and @TheLarkInn as I think the API changed a bit recently.

**Comment by skipjack** [comment]
This might be related to #119, though I'm not 100% on that.

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack/enhanced-resolve/issues/119#issuecomment-634154422
