### ISSUE TITLE
null callback

### ISSUE THREAD

**Issue by wlievens** [webpack/enhanced-resolve#134]
As part of an angular-cli build process, I get the following error:

```
node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40
callbacks[i](err, result);
TypeError: callbacks[i] is not a function
```

I'm well aware this error is not caused by enhanced-resolve itself, since it just accepts the callback, but perhaps a null check could be added to either the `Storage.provide` callback parameter, or null callbacks could be permitted throughout that class? That would make it easier to debug this kind of problem in the future.

**Comment by Luladjiev** [comment]
FYI @angluar/cli v1.6.8 breaks the build. v1.6.7 works fine

**Comment by pjetja** [comment]
I'm getting this error in the same file
```TypeError: Cannot read property 'apply' of undefined
    at /[project]/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by webmaster128** [comment]
See https://github.com/angular/angular-cli/issues/9550 and https://github.com/webpack-contrib/copy-webpack-plugin/issues/217 for the root and workaround.

**Comment by evilebottnawi** [comment]
Not related to `enhanced-resolve`
