### ISSUE TITLE
resolver.hasPlugins is not a function

### ISSUE THREAD

**Issue by srinadh239** [webpack/enhanced-resolve#138]
Webpack v3.11.0 has a dependency on enhanced-resolve v^3.4.1

enhanced-resolve/lib/Resolver.js doesnt have a hasPlugins function which is throwing the error

```
TypeError: resolver.hasPlugins is not a function
```

**Comment by evilebottnawi** [comment]
@srinadh239 Please create minimum reproducible test repo. Thanks!

**Comment by dhaval-lila** [comment]
I am having the same problem any solutions?

**Comment by hsvandreas** [comment]
Same problem here :(

**Comment by evilebottnawi** [comment]
Looks something in your plugins/loaders have incompatibility with `webpack@3`, without reproducible test repo we can't help

**Comment by sokra** [comment]
obsolete with new tapable version
