### ISSUE TITLE
Node engine version should be dropped to v.6.9.0

### ISSUE THREAD

**Issue by thomasmichaelwallace** [webpack/enhanced-resolve#141]
By specifying v.6.11.5 webpack excludes some typical environments, including the AWS Lambda one (currently at 6.10.3).

I looked back at the PR that caused this, and there doesn't seem to be an specific requirement. I've also prepared a PR that bumps it back down to 6.9 (specified by @TheLarkInn) and everything built and tested ok.

See this discussion for further details: https://github.com/webpack/webpack/issues/6579

**Comment by ooflorent** [comment]
Closed by #142
