### ISSUE TITLE
Export Sync methods in SyncAsyncFileSystemDecorator.js

### ISSUE THREAD

**Issue by JulienPradet** [webpack/enhanced-resolve#147]
Hi!

I've noticed that `enhanced-resolve/lib/SyncAsyncFileSystemDecorator.js` did not expose the Sync API.
I wanted to ask you if you would consider a PR that would add something along those lines :
```js
this.statSync = fs.statSync;
this.readdir = fs.readdir;
this.readFile = fs.readFile;
this.readlink = fs.readlink;
this.readJson = fs.readJson;
```

The only negative impact that I see is that it wouldn't motivate people to use the async API in most cases. But I guess we can add a wrapper around each function that prints a warning.

**Comment by sokra** [comment]
This makes sense. Please send a PR

**Comment by sokra** [comment]
fixed
