### ISSUE TITLE
(lib/SymlinkPlugin.js) "resolver.doResolve" can be called many times

### ISSUE THREAD

**Issue by doodadjs** [webpack/enhanced-resolve#154]
# Bug report

**What is the current behavior?**
lib/SymlinkPlugin.js: "resolver.doResolve" can be called many times for a single symbolic link because it does not exit the "forEachBail.withIndex" loop when it encounters an absolute symbolic link.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a new module and use "npm link" to link that module to your project, then create a bundle with Webpack 4. You will have to play with relative vs absolute symbolic links, combine both, etc.

**What is the expected behavior?**
It should exit the loop to resolve the new path.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 10.1.0
Operating System: Windows 10, 64 bits
Additional tools: enhanced-resolve@4.0.0

**Comment by evilebottnawi** [comment]
@doodadjs can you find who is done and fix it?

**Comment by doodadjs** [comment]
@evilebottnawi I don't understand... Do you mean you want me to fix it ?

**Comment by evilebottnawi** [comment]
@doodadjs do you know why it is happens?

**Comment by doodadjs** [comment]
I had the following condition positive twice :
[lib/forEachBail.js#L59](https://github.com/webpack/enhanced-resolve/blob/v4.0.0/lib/forEachBail.js#L59)

Because of :
[lib/forEachBail.js#L54](https://github.com/webpack/enhanced-resolve/blob/v4.0.0/lib/forEachBail.js#L54)

So finally the problem should happen when you have an absolute symlink pointing to another absolute symlink.

**Comment by evilebottnawi** [comment]
@doodadjs can you send PR?

**Comment by doodadjs** [comment]
@evilebottnawi Hmm, I've encountered that when tracing the code to resolve the issue #153. For the moment, I'm not sure of what I should do, that's why I've removed these changes from PR #150 :
[Commit: Revert fix #3 (separate issue) ](https://github.com/webpack/enhanced-resolve/pull/150/commits/b304a41713bb410c4538ea7e400ba790d2067e9a)

Probably we should close it and re-open if someone else encounters it ?

**Comment by doodadjs** [comment]
I'm closing it because we need more certitudes.

**Comment by jwhite878** [comment]
I think I may be having the same problem... were you able to find a solution here?
