### ISSUE TITLE
What are the true default extension options?

### ISSUE THREAD

**Issue by moonformeli** [webpack/enhanced-resolve#158]
Hi, I'm very enjoying to study webpack4. 

In the doc, https://webpack.js.org/configuration/resolve/#resolve-extensions
It says that 
`extensions: ['.wasm', '.mjs', '.js', '.json']`
is the default options for extensions, however, I've tried to look into ResolveFactory.js at line 60, 
I can see
`let extensions = options.extensions || [".js", ".json", ".node"]`
with an annotation "A list of extensions which should be tried for files"

But I 've also found there's an another file named WebpackOptionsDefaults.js which contains
`this.set("resolev.extensions", [".wasm", ".mjs", ".js", ".json"])`

So It seems that is the default options for resolve.extensions. Then what's the code I found from ResolveFactory.js?

**Comment by sokra** [comment]
enhanced-resolve and webpack have different defaults.

enhanced-resolve can be used without webpack, then it uses node.js defaults.

webpack uses defaults for the web.
