### ISSUE TITLE
Flow complainis on `invalidPackageJson/package.json`

### ISSUE THREAD

**Issue by rpominov** [webpack/enhanced-resolve#16]
Hi, I'am truing out Flow, and have a problem with this module. Here what it is outputting:

```
$ flow 
Flow server launched for /Users/anon/projects/my/fluce
Spawned flow server (child pid=87549)
Logs will go to /var/folders/wt/s831gr6j4r38ffydyq0r2ft80000gn/T/flow/zSUserszSanonzSprojectszSmyzSfluce.log
The flow server will be ready in a moment.
Error: flow server is busyzing. If it was just started this can take some time. Retrying... |
Error: flow server is busyzing. If it was just started this can take some time. Retrying... -

/Users/anon/projects/my/fluce/node_modules/karma-webpack/node_modules/webpack/node_modules/enhanced-resolve/test/fixtures/node_modules/invalidPackageJson/package.json:1:3,2: Unexpected end of input

/Users/anon/projects/my/fluce/node_modules/webpack/node_modules/enhanced-resolve/test/fixtures/node_modules/invalidPackageJson/package.json:1:3,2: Unexpected end of input

Found 2 errors
```

As far as I understand, it scanning `/node_modules/` for some reason, and fails on your broken fixture module. Could you, perhaps, exclude tests from npm package, by adding them in `.npmignore`? If you could do that, that would be great!

**Comment by adjohu** [comment]
Yeah I'm having issues with this as well.

**Comment by rpominov** [comment]
I've solved this by adding following to `.flowconfig`:

```
[ignore]
.*/enhanced-resolve/test/fixtures/node_modules/invalidPackageJson
.*/phantomjs/node_modules/npmconf/test/fixtures/package.json
.*/npm-pkg
```

Had to add couple others, btw.
And note that an ignore string is a regexp, I didn't get it at first.

**Comment by bendman** [comment]
The pull request #19 should fix this issue, still waiting on feedback. This breaks the Flattener package, which flattens the node_modules folder to stop breaking on Windows.
