### ISSUE TITLE
`isAbsolutePath()` sometimes doesn't work on Windows

### ISSUE THREAD

**Issue by asyncmax** [webpack/enhanced-resolve#166]
On Windows, when using `bash` instead of `cmd.exe`, Node's `process.cwd()` returns the drive letter in lowercase in some circumstances. This makes the following code fail.

https://github.com/webpack/enhanced-resolve/blob/5c1495a947060cf11106abc325b8adf1a0eff9b1/lib/ResolverFactory.js#L320

The RegExp must be changed to `/^[A-Za-z]:|...` so it can handle lowercase drive letters correctly.

This problem can result in the binding to a wrong version inside the output bundle of Webpack when `resolve.modules` has an absolute path in it.

**Comment by evilebottnawi** [comment]
@asyncmax feel free to send a PR with tests

**Comment by sokra** [comment]
fixed
