### ISSUE TITLE
fails if extension missing in browser field left side

### ISSUE THREAD

**Issue by mvayngrib** [webpack/enhanced-resolve#17]
hey guys, ran into this issue:

works:

```json
  "browser": {
    "./lib/blah.js": false
  }
```

doesn't

```json
  "browser": {
    "./lib/blah": false
  }
```

**Comment by sokra** [comment]
What does the spec say?

**Comment by mvayngrib** [comment]
it's not exactly an official spec, do you mean this? https://gist.github.com/defunctzombie/4339901

if so, the spec doesn't specify whether you need extensions or not, though the examples provided do have them

**Comment by sokra** [comment]
> The left hand side (key) is the name of a module or file ...

hmm... `name of file`... not sure... I would interpret it as it should be a file name not a request string.

cc @defunctzombie

**Comment by mvayngrib** [comment]
i'd say there's some precedent for support as node's require is lenient in this respect: you can require('./blah) or require('./blah.js')

**Comment by sokra** [comment]
Propably fixed
