### ISSUE TITLE
Clear documentation

### ISSUE THREAD

**Issue by JoviDeCroock** [webpack/enhanced-resolve#171]
Hey,

This title might come across the wrong way, no harm meant I know it's hard to keep these things up-to-date but I've been hopelessly trying to write a webpack-plugin to rewrite a resolve request but it seems that I have to go through all of the code to achieve this, I know it's tapable and going to pipelines to see what I can tap into isn't that hard but how it works is a bit more complex.
If this is not possible it would be great to just have an entry about this or something since the documentation at this point is quite sober. Which is understandable since this is a pretty complex process.

**Comment by JoviDeCroock** [comment]
Allright I have figured out on how to do these things, where can I contribute documentation best?

**Comment by evilebottnawi** [comment]
@JoviDeCroock just a PR
