### ISSUE TITLE
[Question] - custom fs implementation

### ISSUE THREAD

**Issue by dazinator** [webpack/enhanced-resolve#172]
Hello,

I would like to use an alternative underlying `fs` implementation, such as `memfs` or `unionfs`
I am not sure If I can do this, as [NodeJsInputFileSystem](https://github.com/webpack/enhanced-resolve/blob/95e27d33d052fe955d297c6165111cfd0cc03240/lib/NodeJsInputFileSystem.js) seems to be harcoded to use a particular underlying `fs` implementation. What would be the best way to go about this? Thanks

**Comment by evilebottnawi** [comment]
Send a PR to allow setup own fs

**Comment by dazinator** [comment]
Currently, the methods that access `fs` are defined at the prototype level: 

https://github.com/webpack/enhanced-resolve/blob/95e27d33d052fe955d297c6165111cfd0cc03240/lib/NodeJsInputFileSystem.js#L42

I think I'd need to remove that and have them declared at the class instance level, so that if a custom `fs` is passed in the constructor then that can be used, otherwise fall back to default `fs` implementation based on the `graceful-fs`. Does this sound ok with you?

**Comment by evilebottnawi** [comment]
Yes

**Comment by dazinator** [comment]
Great. PR Submitted.

**Comment by sokra** [comment]
fixed, you can pass a `fileSystem` i. e. `fs` or `memfs`
