### ISSUE TITLE
Can't find any documenatation

### ISSUE THREAD

**Issue by callumlocke** [webpack/enhanced-resolve#18]
The documentation link points to the front page of the Webpack wiki, which then links to the Webpack website. I can't find any documentation about what this module does or how to use it (although it looks very useful from looking at the code).

I want to know:
- Does this implement defunctzombie's [browser field spec](https://gist.github.com/defunctzombie/4339901)?
- If so, am I correct in understanding that enhanced-resolve is basically similar to [browser-resolve](https://github.com/defunctzombie/node-browser-resolve), but with the added ability to provide your own filesystem to mediate/handle disk access?

It would be good to see at least one usage example in the readme.

**Comment by sokra** [comment]
> Does this implement defunctzombie's browser field spec?

yes

> If so, am I correct in understanding that enhanced-resolve is basically similar to browser-resolve, but with the added ability to provide your own filesystem to mediate/handle disk access?

yes, similar. Plugin based.

**Comment by mark-slepkov** [comment]
Hello friends. I'm using bower in my projects and I writing a bower modules which will be check in my projects.
Usually it is a simple modules which is have one entry point. And my bower.json looks like` {..., main: 'src/entry_point.js', ..}`. And my webpack config have the strings: ```
plugins: [
                new webpack.ResolverPlugin([
                            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
                        ],
                        ["normal", "loader"]
                )
            ]
``` 
In a code of my project I write something like:
`require('my_awesome_library')` 
But now I want to write a big module which will have several entry points and I want to write:
```
require('my_awesome_module/library_for_fun')
require('my_awesome_module/just_another_fine_library')
``` and so on.
how can I check this module in webpack config? Please help.

**Comment by grrowl** [comment]
:+1: 

Can't find any documentation about a migration path from Webpack v1 -> v2. I'm trying to incorporate the (component-resolver-webpack)[https://github.com/toptal/component-resolver-webpack/] plugin but there's no documentation about it.

**Comment by mikesherov** [comment]
Thanks for contributing, everyone! I'm going to consider this issue closed for now. If there are any specific documentation asks, please feel free to open a new issue (or even better a pull request on README).
