### ISSUE TITLE
Chunk related resolver

### ISSUE THREAD

**Issue by webdeb** [webpack/enhanced-resolve#180]
Hi, I am trying to implement a `ContextualVariantResolverPlugin`. Which will load a variant of a module, based on the branch context:

```
┌──────────────────────────────────────────────────────────┐
│                                                          │
│                         index.js                         │
│                                                          │
└──────────────────────────────────────────────────────────┘
                              │                             
             ┌────────────────┴───────────────┐             
             │                                │             
             ▼                                ▼             
┌─────────────────────────┐      ┌─────────────────────────┐
│                         │      │                         │
│      mobile/App.js      │      │     desktop/App.js      │
│                         │      │                         │
└─────────────────────────┘      └─────────────────────────┘
             │                                │             
             │                                │             
             ▼                                ▼             
 ┌────────────────────────┐      ┌─────────────────────────┐
 │                        │      │                         │
 │      MobileNav.js      │      │         Nav.js          │
 │                        │      │                         │
 └────────────────────────┘      └─────────────────────────┘
              │                               │             
              │                               │             
              │                               │             
              │                               │             
              │   ┌────────────────────────┐  │             
              │   │                        │  │             
              └──▶│        Page.js         │◀─┘             
                  │                        │                
                  └────────────────────────┘                
                               │                            
                               │                            
                               │                            
                               │                            
                               ▼                            
                      ┌─────────────────┐                   
                      │                 │                   
                      │     Button      │                   
                      │                 │                   
                      └─────────────────┘                   
                               │                            
                               │                            
                               │                            
                  ┌────────────┴───────────┐                
                  │                        │                
                  │                        │                
                  ▼                        ▼                
         ┌─────────────────┐      ┌────────────────┐        
         │Button/mobile.js │      │Button/index.js │        
         └─────────────────┘      └────────────────┘        
```

So, depending on the branch `desktop/App.js` or `mobile/App.js` the `Button` component should load either from index.js (default) or mobile.js.

Of course I am not willing to implement the logic for every component like button / input etc. Instead, I thought there should be a way to provide the information of the current Tree to the resolver plugin inside. So the logic would be like:

```
if (mobileTree) {
  tryToLoadMobileVariant(request..)
}
```

But unfortunately I could't find where I could read this **Tree** information from.

**Comment by webdeb** [comment]
Maybe there is a way to provide some information to the resolver about the import Stack. 
For example: 
```
request.path = "Button"
request.context.importStack = [
  // index.js
  // mobile/App.js
  // Page.js
]
```

Or even better, provide a field, where one could put its flags on, like: when trying to resolve `src/**mobile**` -> request.context.flags.isMobile = true

So that request.context.flags are provided to the dependencies down the road when resolving.

**Comment by marvinhagemeister** [comment]
Whilst something like this could theoretically work, it makes me wonder if there are any easier solutions to this.

One thing that springs into mind is that since you're doing the branching via feature detection on the client you could reuse that gained knowledge. Let's say you're building some sort of (p)react application. There you could pass the results of the feature detection around via context and chose the right branch in `Button.js` based on that during runtime.

**Comment by webdeb** [comment]
Yes, I could decide dynamically, but I would loose the benefits of the chunking, right? The main idea here is to switch the resolver to another module by the current chunk. In my index.js is the following:

```
const loaders = {
  mobile: () => import(/* webpackChunkName: "mobile" */ './mobile/App'),
  desktop: () => import(/* webpackChunkName: "desktop" */ './App'),
}

const initialize = () => {
  render({ default: BigLoader })

  const appPromise = isMobile() ? loaders.mobile() : loaders.desktop()
  const i18nPromise = loadI18n()

  Promise.all([appPromise, i18nPromise]).then(([app, i18n]) => {
    render(app, i18n)
  })
}

initialize()

```

So, I was thinking, if I could switch the resolver, when the current compilation is for the mobile branch, and just load/use mobile compoents, this would be very beneficial.

**Comment by webdeb** [comment]
I am wanted to separate it this way, to accomplish 2 things. 
1. to have only one build
2. to separate the mobile application from desktop and vice-versa, because I am using Ionic for some mobile stuff, which I don't want to include into the desktop bundle.

**Comment by piglovesyou** [comment]
I'm not 100% sure to get your idea but it's nice to have less sized bundle.

How about just having multiple webpack configs using [multi compiler](https://github.com/webpack/webpack/tree/master/examples/multi-compiler#webpackconfigjs)

```js
const mobleConfig = {
  resolve: {
    modules: [
      path.join(__dirname, './src/components/mobile'),
      path.join(__dirname, './src/components'),
      'node_modules',
    ]
  }
};

const desktopConfig = {
  resolve: {
    modules: [
      path.join(__dirname, './src/components'),
      'node_modules',
    ]
  }
}
```

Or if you prefer `alias`, [try early access version of my `AliasPlugin`](https://github.com/webpack/webpack/issues/6817#issuecomment-505969374).

**Comment by sokra** [comment]
Resolving is not done for every path of the application. i. e. in your example `Button` will only resolved once from `Page.js` and this is independent of the path it came from. Modules do not depend on the Chunk they are included in.

If you want to have different resolving depending on mobile/desktop use the approach @piglovesyou mentioned: https://github.com/webpack/enhanced-resolve/issues/180#issuecomment-506213018
