### ISSUE TITLE
Typescriptify enhanced-resolve

### ISSUE THREAD

**Issue by vankop** [webpack/enhanced-resolve#184]
## Feature request

It will be great to support typescript. Related to https://github.com/webpack/webpack/issues/3277 and https://github.com/webpack/webpack/issues/9196

**What is motivation or use case for adding/changing the behavior?**

documentation

**How should this be implemented in your opinion?**

Adding tsconfig, adding typescript as dev dependency. Maybe create typescript definitions as `webpack-source` does, something like `@types/webpack-enhanced-resolve`

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by sokra** [comment]
You can do it the same way as webpack uses types:

* JSDocs with type info
* lint step which runs `tsc --noEmit` to check the types
