### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by Amirh24** [webpack/enhanced-resolve#193]
Seems like current code creates issues with TypeScript.

enhanced-resolve/lib/Resolver.js:254
                const idxQuery = identifier.indexOf("?");
                                            ^

TypeError: identifier.indexOf is not a function

And also:

enhanced-resolve/lib/AliasFieldPlugin.js:29
                        const data2 = fieldData[innerRequest.replace(/^\.\//, "")];
                                                             ^
TypeError: innerRequest.replace is not a function

Seems like adding toString() before indexOf and replace fixes this issues

**Comment by evilebottnawi** [comment]
Do you use `enhanced-resolve` directly?

**Comment by Amirh24** [comment]
No. it gets called as part of Storybook

**Comment by evilebottnawi** [comment]
Can't reproduce

**Comment by Amirh24** [comment]
Not sure why. This occurs:
<img width="1647" alt="Screen Shot 2019-08-13 at 10 08 45" src="https://user-images.githubusercontent.com/16143361/62921847-85e95300-bdb2-11e9-9088-feb42c2a7d5c.png">
And when adding toString() before the indexOf it's fine and it goes on to the .replace error. When adding a toString() there all seems to be fine

**Comment by evilebottnawi** [comment]
@Amirh24 something buggy on storybook side, can you create minimum reproducible test repo?

**Comment by Lucas-Geitner** [comment]
Same issue with react styleguidist or expo for react native web

**Comment by evilebottnawi** [comment]
Problem still exists?
