### ISSUE TITLE
Curious about the Resolver.js in enhanced-resolve

### ISSUE THREAD

**Issue by eret9616** [webpack/enhanced-resolve#196]
in  a normal resolver, 

Resolver.js:
```
...
parse(identifier) {
      ...
      const part = {
			request: "",
			query: "",
			module: false,
			directory: false,
			file: false
		};
   	...
       part.module = this.isModule(part.request);
       part.directory = this.isDirectory(part.request);
       ...
}
...
```

ParsePlugin.js:
```
...
     //     ↓ that 'part' obj
    if (parsed && resolveContext.log) {
		if (parsed.module) resolveContext.log("Parsed request is a module");
	        if (parsed.directory) resolveContext.log("Parsed request is a directory");
     }
...
```

Will the 'file' property in 'part' obj change?

e.g:
 i have index.js in src/ and set 

demo.js:
```
...

const compiler =  Webpack({entry:'./src/index.js'})

compiler.run((err,stat)=>{ })
```
 running webpack, didnt see the property change('file' is still false) in resolve process even in the 'ResultPlugin'

**Comment by evilebottnawi** [comment]
Can you clarify, what is problem?

**Comment by eret9616** [comment]
hi  i'm newbie ,try to read the code,  i wonder what 'file' property do , it's 'false' all the time  didnt see it become 'true'

**Comment by evilebottnawi** [comment]
It is internal module in webpack please provide use case, thaks

**Comment by evilebottnawi** [comment]
@eret9616 because entry is absolute path to entry, it is allow to avid misleading what entry should be get, because you can have `main.js` and `main.css` and etc
