### ISSUE TITLE
Wrong Webpack module resolution in Angular apps

### ISSUE THREAD

**Issue by DimitarTachev** [webpack/enhanced-resolve#197]
Investigating a wrong Webpack module resolution in Angular apps, we found out that it's caused by a [getInnerRequest call](https://github.com/angular/angular-cli/blob/17540a2e4be9d72579ccc06978727047f375d551/packages/ngtools/webpack/src/paths-plugin.ts#L53) to the latest version of the enhanced-resolve plugin (v4.1.0).

Problematic code:

``` JavaScript
const { ResolverFactory } = require("enhanced-resolve");
const myResolver = ResolverFactory.createResolver({});
console.log(myResolver.join(".", "../myRelativePath"));
// expected output: `../myRelativePath`
// actual output: `myRelativePath`
```

In `enhanced-resolve@5.0.0-beta.3`, the issue is resolved by the 
> refactor join and normalize to use node.js path instead of memory-fs

part of this PR -  https://github.com/webpack/enhanced-resolve/pull/182.

**Comment by sokra** [comment]
True, in v4 `join` only supports absolute paths as first argument.

**Comment by sokra** [comment]
The problem is in `memory-fs/lib/normalize`. The new major no longer uses this.

**Comment by sokra** [comment]
seems like there is a PR for this: https://github.com/webpack/memory-fs/pull/33

This package didn't get as much love as it would have needed...

**Comment by sokra** [comment]
fixed: https://github.com/webpack/enhanced-resolve/releases/tag/v4.1.1
