### ISSUE TITLE
Unexpected resolve results

### ISSUE THREAD

**Issue by acrazing** [webpack/enhanced-resolve#199]
I cannot find out the reason, but the result is:

In one webpack instance, the resolve result is different with same request format in different module:

The first and second one screenshot are third party javascript module in node_modules, the last one is local typescript module.

all the request format is `import { xxx } from 'react-router'`.

The result is: first one resolved `cjs` entry, but the others resolved `esm` entry.

![image](https://user-images.githubusercontent.com/10029810/66703157-18ba5580-ed42-11e9-92c1-a51bddd5f228.png)
![image](https://user-images.githubusercontent.com/10029810/66703223-e3623780-ed42-11e9-94d8-ed46eccea669.png)
![image](https://user-images.githubusercontent.com/10029810/66703185-5f0fb480-ed42-11e9-9f31-3f0cd4c6e4da.png)

**Comment by sokra** [comment]
Resolving from `.mjs` files is different. They do not support the `module` field in package.json.

**Comment by acrazing** [comment]
I see, thanks.

**Comment by VisonM** [comment]
@sokra hello sokra. I'm stuck in a similar problem these days. I was wondering if you could answer my question when you have time, thanks a lot.❤️

### introduction

`webpack version:4.46.0`
`enhanced-resolve version:4.5.0`

I use [`vue-i18n-composable`](https://github.com/intlify/vue-i18n-composable) in a web project base on [`@vue/composition-api`](https://github.com/vuejs/composition-api)

```
// vue-i18n-composable/package.json
{
   "module": "dist/index.mjs" // it will use this field when we import vue-i18n-composable in webpack build
}
```

```js
// vue-i18n-composable/dist/index.mjs

/*  this file import @vue/composition-api
* but it resolve result is node_modules/@vue/composition-api/index.js,this is wrong❌
*/
import {computed, getCurrentInstance} from "@vue/composition-api"; 
```

```js
// a simple vue component

/*  this file also import @vue/composition-api
* but it resolve result node_modules/@vue/composition-api/dist/vue-composition-api.mjs  this is correct🌈
*/
import {computed} from "@vue/composition-api"; 
```

more detail in this pr https://github.com/intlify/vue-i18n-composable/pull/15

However,I can't reproduct in webpack2 and webpack5.

### my question
* Is this a webpack4 bug?
* Will webpack handle files with `.mjs` suffix specially?
* what caused this problem
* Based on webpack4 how should I solve it
