### ISSUE TITLE
NPM license is "none"

### ISSUE THREAD

**Issue by Vadorequest** [webpack/enhanced-resolve#202]
There seems to be an issue with the license declared on NPM.

https://www.npmjs.com/package/enhanced-resolve
![image](https://user-images.githubusercontent.com/3807458/68546559-e3a03200-03d7-11ea-934b-787097bbaa94.png)

The license is clearly MIT: https://github.com/webpack/enhanced-resolve/blob/master/LICENSE

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by Vadorequest** [comment]
Well, I don't have time, and I don't see what's wrong either.

The package https://github.com/webpack/enhanced-resolve/blob/master/package.json does specify "LICENSE" in "files", so it should be included when releasing to npm.
