### ISSUE TITLE
Webpack 5 pnpapi not found

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/enhanced-resolve#210]
I'm currently upgrading Next.js to Webpack 5 and running into this issue. When I try and run a serverless build. I'm not sure if this is an enhanced resolve issue or a problem on my side.

Heres the Webpack config. https://github.com/module-federation/next.js/blob/a4653af43d10b67bab77d53943ba27ab155d8c1e/packages/next/build/webpack-config.ts which uses pnp-webpack-plugin

https://github.com/module-federation/next.js/blob/a4653af43d10b67bab77d53943ba27ab155d8c1e/packages/next/lib/resolve-request.ts#L1-L20

```js
import resolve from 'next/dist/compiled/resolve/index.js'
import path from 'path'

export function resolveRequest(req: string, issuer: string) {
  // The `resolve` package is prebuilt through ncc, which prevents
  // PnP from being able to inject itself into it. To circumvent
  // this, we simply use PnP directly when available.

  if (process.versions.pnp) {
    const { resolveRequest } = require(`pnpapi`)

    return resolveRequest(req, issuer, { considerBuiltins: false })
  } else {
    const basedir =
      issuer.endsWith(path.posix.sep) || issuer.endsWith(path.win32.sep)
        ? issuer
        : path.dirname(issuer)
    return resolve.sync(req, { basedir })
  }
}
```

```json
"errors": [
    {
      "moduleIdentifier": "/Users/zjackson/ramdisk/dev/next.js/node_modules/enhanced-resolve/lib/ResolverFactory.js",
      "moduleName": "../../node_modules/enhanced-resolve/lib/ResolverFactory.js",
      "loc": "74:11-28",
      "message": "Module not found: Error: Can't resolve 'pnpapi' in '/Users/zjackson/ramdisk/dev/next.js/node_modules/enhanced-resolve/lib'"
    }
  ]
}
```

**Comment by evilebottnawi** [comment]
webpack@5 support pnp out of box, can you disable `pnp-webpack-plugin`?

**Comment by ScriptedAlchemy** [comment]
Ohhh magical! Should I keep the code pasted above still or will that be compatible with the internalized solution. (I’m not familiar with pnpapi)

**Comment by evilebottnawi** [comment]
Remove it

**Comment by ScriptedAlchemy** [comment]
Perfect! Thank you!

**Comment by evilebottnawi** [comment]
@ScriptedAlchemy Can we close the issue?

**Comment by ScriptedAlchemy** [comment]
Yes

**Comment by kksweet8845** [comment]
@ScriptedAlchemy  Did you solve the problem? I got the same issue.

**Comment by evilebottnawi** [comment]
@kksweet8845 update webpack to latest stable version

**Comment by lid3rs** [comment]
Having the same issue and using webpack 5.4.0

**Comment by evilebottnawi** [comment]
You should not `require('pnpapi')`

**Comment by CRGavrila** [comment]
I don't think they use pnpapi, this error happens to me also when target: node

**Comment by xinaesthete** [comment]
I'm getting this error when I try to use Webpack 5.4.0 to build a module which itself calls the Webpack API.  I do not `require('pnpapi')` directly.  (Also get quite a few `request of a dependency is an expression` and `require function is used in a way in which dependencies cannot be statically extracted` warnings).

**Comment by evilebottnawi** [comment]
> Perhaps I should make Webpack external (not a webpack expert by any means). edit that seems to work in my case, seems fair enough.

Yep, but what is real use case? Building webpack and webpack stuff is not easy, but it is possible, maybe you can provide more infromation?

**Comment by xinaesthete** [comment]
It's a live-coding / rapid-prototyping type environment where user can write a module that is reloaded into the system.  This would probably be achievable with a more standard use of HMR, but unfortunately refactoring the code such that it would fit into a more standard webpack build will be more work, I believe.

**Comment by xinaesthete** [comment]
So as of now, the part of the system that has been built with Webpack for a while is the server (which is relatively simple, written as ES modules in TypeScript).  I'm trying to change it so that there is some new functionality there for running a webpack build of some module that is written / requested at runtime.  I have a simple test JS script for calling the Webpack API, which is working fine - so I'm reasonably sure that the actual Webpack functionality I'm trying to invoke shouldn't be too much of a challenge.

I was a bit optimistic earlier when I said that making Webpack external had allowed my webpack calls in the actual TS server code to work, though.  I'm sure it's a lack of understanding on my part, but currently I have
```
    externals: [
        {
            webpack: { 
                commonjs: "webpack",
                module: "webpack" 
            }
        }
    ]
```
in my webpack config, which stops the build warnings / error, but fails to allow me to either require or import webpack.

I'll keep plugging away, but any input is much appreciated.

**Comment by xinaesthete** [comment]
`wepack: "commonjs2 webpack` seems to do the trick.

**Comment by Cauany** [comment]
Hey, how was this problem resolved? I'm having the same problem. Could someone help me? I don't understand how it was solved.

**Comment by xinaesthete** [comment]
@Cauany in my particular case, I actually switched to using `esbuild` instead and it did what I wanted & runs waaaay faster than WebPack, but that is not to say that it is a general replacement in all cases.

I think what I meant in my previous comment was that I had
```
externals: [ { webpack: "commonjs2 webpack" } ]
```
in my configuration and I momentarily thought it solved my problem... but actually I might have still had a runtime error or something.  Memory is hazy.  I definitely switched away from WebPack for that specific thing (and was happy with my choice).


  Good luck, though.

**Comment by Cauany** [comment]
Ok, Thank you!!!
