### ISSUE TITLE
Filesystem cache is never cleared based on duration when running completely synchronously

### ISSUE THREAD

**Issue by jomi-se** [webpack/enhanced-resolve#229]
Hello 👋 

I was investigating very high memory usage in https://github.com/sverweij/dependency-cruiser and memory profiling pointed towards this library.

Dependency-cruiser uses this library in a completely synchronous fashion while crawling the file system to gather dependencies. A (several) `CachedInputFileSystem` are instantiated with a `4000` duration.

However, given that during the tool's lifecycle is synchronous, the `this.tick` function is never called by the timer set with `setInterval()` so the memory usage by the cache grows until everything is cached.

For example, when running `dependency-cruiser` on itself, this cache takes up around 230Mb of memory according to chrome devtools before exiting.

Given that this module has a synchronous API I believe this cache should also be cleared synchronously when needed. Would it be possible to add some code [here](https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js#L75) in `finishedSync()` that would conditionally call `this.tick()` if the this.duration has been exceeded ?

Thank you 🙌

**Comment by evilebottnawi** [comment]
Yep, memory leak, we need to fix it, you can be the champion of this :star:

**Comment by jomi-se** [comment]
Thanks a lot for your work @sokra ! <3

I was about to start working on a PR 😅 

Will this be included in enhanced-resolve v4 or will you push it to v5 ?

**Comment by evilebottnawi** [comment]
It is for v5, do you want to backport?

**Comment by jomi-se** [comment]
If it is not too much trouble, yes please 🙏   (unless you're planning to release in the next couple of days)

This greatly reduces the strain on our CI that is a bit memory-limited, but we'd like to keep on using `dependency-cruiser`

Btw, with the latest version we got a pretty decent performance improvement alongside the memory leak fix. Dependency-cruiser runs ~17% faster with the latest `enhanced-resolve` commit 🎉 

Good job and thank you!

**Comment by evilebottnawi** [comment]
> Btw, with the latest version we got a pretty decent performance improvement alongside the memory leak fix.

Do you about `neo-async` memory fix or fix in master package for webpack@5?

**Comment by jomi-se** [comment]
I'm not sure what you mean @evilebottnawi 

I'm just directly using `enhanced-resolve` inside `dependency-cruiser`. 

I tested the latest version by using `    "enhanced-resolve": "webpack/enhanced-resolve#master",` in `dependency-cruiser's `package.json`

**Comment by sokra** [comment]
> unless you're planning to release in the next couple of days

do you mean a beta version or a stable v5 version?

I'm fine with releasing either of them. We can just go to v6 if needed...

**Comment by jomi-se** [comment]
>do you mean a beta version or a stable v5 version?

I was asking about a stable v5, but if a beta release is good enough for @sverweij (dependency-cruiser's author) then it's good enough for me.

The perf improvements are very nice, so it'd be cool to get them in addition to this fix @sokra Whatever suits you best

**Comment by sverweij** [comment]
If I'd have any say in it I would prefer a stable version; either a back port to v4 or a v5 release - whichever is most comfortable for you.

B.t.w. the performance improvements between v4 and v5/ _master_ are impressive - thank you @sokra for the hard work that went into that!
