### ISSUE TITLE
incorrect resolve

### ISSUE THREAD

**Issue by vankop** [webpack/enhanced-resolve#238]
Good day!

Is there a possibility that the `resolve.modules` implementation changed in webpack5? I upgraded my project and after a few struggles I found out that I have to change this option to make it work.

Here are a few details to the problem:
This is how the webpack `resolve` object looks in webpack4.
```js
resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    alias: {
      src: path.resolve('./src'),
    },
    modules: ['src/b',  'src/a', 'src/common', 'node_modules'],
},
```

The file structure of my project:
```
project/
└── src/
     ├── common/
     │   └── config/
     │       └── myObjectFile.js
     ├── a/
     │   ├── config.js
     │   └── config/
     │       └── someOtherFile.js
     └── b/
```
<details>
  <summary>The content of the <code>./src/common/config/myObjectFile.js</code> file:</summary>

```js
export default {
  someProp: {
    //...
  },
  //...
}
```

</details>

<details>
  <summary>The content of the <code>./src/a/config.js</code> file:</summary>

```js
const config = {
  configA: {
    //...
  },
  //...
};

module.exports = config;
```

</details>

In the project I do a import which looks like this: 
```js
import myObject from 'config/myObjectFile';
```
This should and is resolved in webpack4 like this: `./src/common/config/myObjectFile.js`. 
In webpack5 on the other hand I'm getting this: `./src/a/config.js`.

Only after I changed (reversed) the order of the `resolve.modules` array it worked as intended:
```js
resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    alias: {
      src: path.resolve('./src'),
    },
    modules: ['node_modules', 'src/common', 'src/a', 'src/b'],
},
```

Is this intended behavior? 
Is my "fix" even valid or is the problem something completely different?

Thank you!

_Originally posted by @KingSora in https://github.com/webpack/webpack/issues/9802#issuecomment-677401611_

**Comment by KingSora** [comment]
@vankop Thanks for creating this issue! I've attached you the repo. 
Run `yarn` and then `yarn dev` to install and start it.

Inside the repo you can find the file `packages/project/src/common/App.js`. Inside this file I'm importing:
```js
import myObject from 'config/myObjectFile';
```
I'm printing the strigified object to the DOM. 

With webpack `"webpack": "5.0.0-beta.27"` I'm getting the object from the file `packages/project/src/a/config.js`.
With webpack `"webpack": "4.44.1"` I'm getting the object from the file `packages/project/src/common/config/myObjectFile.js`. (as it should be).

[webpack_resolve.zip](https://github.com/webpack/enhanced-resolve/files/5116515/webpack_resolve.zip)

**Comment by vankop** [comment]
@KingSora thanks, finally have reproduced in https://github.com/webpack/enhanced-resolve/pull/240/files
