### ISSUE TITLE
TypeError: Cannot read property 'query' of null in /enhanced-resolve/lib/ParsePlugin.js:19:43 when using xlsx

### ISSUE THREAD

**Issue by cmartinez1499** [webpack/enhanced-resolve#239]
A React Application using Webpack getting this error after installing xlsx package with npm
changing: 
```javascript
			if(request.query && !parsed.query) {
				obj.query = request.query;
			}
```
 to 
```javascript
			if(request.query && (parsed && !parsed.query)) {
				obj.query = request.query;
			}
```
fixes this issue.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by cmartinez1499** [comment]
here is a repo with the same error. 
https://github.com/cmartinez1499/xlsxIssueReplication

**Comment by sokra** [comment]
It's cased by that line:

https://github.com/cmartinez1499/xlsxIssueReplication/blob/a809c49d076083e1e4a59b633a4e3c15b9518439/webpack.config.js#L52

```
resolve.alias: { "./dist/cpexcel.js": "" }
```

What should this line do?

**Comment by sokra** [comment]
Anyway the problem is fixed in the next major version.

**Comment by evilebottnawi** [comment]
Fixed
