### ISSUE TITLE
Cannot resolve files in folders named `#`

### ISSUE THREAD

**Issue by goto-bus-stop** [webpack/enhanced-resolve#247]
This is quite uncommon, but at least one module with millions of downloads per week has folders named `#`:

https://github.com/medikoo/es5-ext/blob/3ddd2066b19e7c25a782869a304ae35d8188c8f1/string/%23/at.js

With the new enhanced-resolve, `require('es5-ext/string/#/at')` resolves to `es5-ext/string/index.js#/at` instead of `es5-ext/string/#/at.js`.

Try it by doing:
```bash
npm install es5-ext enhanced-resolve
$EDITOR index.js
```

```js
// index.js
var resolve = require('enhanced-resolve')
console.log(
  resolve.sync(process.cwd(), 'es5-ext/string/#/at'))
// → es5-ext/string/index.js#/at
```

```bash
node index
```

**Comment by evilebottnawi** [comment]
@vankop I think we should use this logic only for es imports

**Comment by vankop** [comment]
cc @sokra 

@evilebottnawi we decided to be consistent, so in example above `#/at` will be hash

**Comment by evilebottnawi** [comment]
@vankop I am afraid that this may create a lot of problems, I have seen quite a few packages using `#` :disappointed:

**Comment by goto-bus-stop** [comment]
I don't know if it's explicitly specified one way or the other, but (almost) none of the existing CommonJS code expects require paths to be treated as URLs.

**Comment by vankop** [comment]
@goto-bus-stop this is webpack specific, take a look into https://webpack.js.org/concepts/loaders/#inline

**Comment by goto-bus-stop** [comment]
@vankop I don't understand how that relates to `#`…if it's about `?` also being treated specially, the difference is that `?` is not widely used in the wild, while `#` _is_ in use in the wild and treating it specially breaks compatibility with existing modules.

**Comment by evilebottnawi** [comment]
@vankop maybe we can do `fs.stats` when request contains special characters and check is a directory/file?

**Comment by goto-bus-stop** [comment]
@evilebottnawi did you intend to close this?

**Comment by evilebottnawi** [comment]
@goto-bus-stop sorry

**Comment by goto-bus-stop** [comment]
I think this was fixed in https://github.com/webpack/enhanced-resolve/pull/255? Thanks!
