### ISSUE TITLE
Having a hard time implementing the multi-path alias

### ISSUE THREAD

**Issue by stephane-lou** [webpack/enhanced-resolve#250]
Hi.

I have some class where I have to require other javascript files based on an alias I have implemented using the "multi path" alias method.

Let's just take the example I found that led me using this plugin in the first time:

```
import AliasPlugin from 'enhanced-resolve/lib/AliasPlugin';

const config = {
  resolve: {
    plugins: [ new AliasPlugin('described-resolve', [
      { name: 'mySingleAlias', alias: '/path/to/alias' },
      { name: 'myMultiAlias', alias: [
        '/path/to/try/first',
        '/path/to/try/second',
        '/path/to/try/last',
      ]},
    ], 'resolve') ],
  },
};
```

Now, in my other javascript, I have a "plugin list" in an array where I do this, for the sake of the example let's just say plugin1.js is in `/path/to/try/first` and plugin2.js is in `/path/to/try/second`

```
    const plugins = ['plugin1.js','plugin2.js'];
    for (const i in plugins) {
        const pluginPath = plugins[i];
        const plugin = require(`myMultiAlias/${pluginPath}`);
// do something with the required plugin
    }
```

When doing this, only requiring the plugin1.js works, the second tries to also requiring it from `/path/to/try/first`.

Do I have misunderstood this plugin's goal and/or how to achieve what I try to do ?

**Comment by evilebottnawi** [comment]
You can solve it in own code, for example (pseudo code):
```js
function resolveRequests(context, possibleRequests, resolve) {
  if (possibleRequests.length === 0) {
    return Promise.reject();
  }

  return resolve(context, possibleRequests[0])
    .then((result) => {
      return result;
    })
    .catch((error) => {
      const [, ...tailPossibleRequests] = possibleRequests;

      if (tailPossibleRequests.length === 0) {
        throw error;
      }

      return resolveRequests(context, tailPossibleRequests, resolve);
    });
}
```

**Comment by titpetric** [comment]
I have similar issues, and I don't see how `resolveRequests` should help me somehow. How could I get a resolved filename from an input filename on an AliasPlugin object instance?

I'm trying to define `@theme` that aliases to `theme/${THEME}/` or `theme/default/` as a fileback, similarly to what the original issue description suggests - some files exist in the first location, and the second location is used as a fallback. The alias won't resolve and I can't figure out how I can test the resolver by hand, or even how to write a custom resolver.

I'm trying to do this against a webpack@4 project, I can share some code for it but it's basically the same as the [sources GH comment on this issue](https://github.com/webpack/webpack/issues/6817#issuecomment-542448438) and the opened up issue here. Ultimately, the alias I'm defining won't even resolve.

**Comment by titpetric** [comment]
Following up, I think my main issue is with hot-loading. If I declare top-level imports into the various .vue/js source files, the file is loaded correctly, but if I do a callback e.g. `() => import('@theme/Commmon/Navigation.vue')` then the compiler/runtime screams at me.

**Comment by MrSnoozles** [comment]
Have you found a solution for this problem?

**Comment by zecka** [comment]
Got same issue than @MrSnoozles . Did you find a solution with hot reloading ?

**Comment by alexander-akait** [comment]
It can be solved by:
```
alias: {
  myMultiAlias: ["b", "c", "d", "e", "a"],
}
```
