### ISSUE TITLE
Package path . is not exported from package

### ISSUE THREAD

**Issue by martpie** [webpack/enhanced-resolve#283]
Hello 👋

While trying to solve https://github.com/martpie/next-transpile-modules/issues/147, I realized the problem was most probably coming from `enhanced-resolve`.

Here's a snippet:

```js
const enhancedResolve = require('enhanced-resolve');
const process = require('process');

const resolve = enhancedResolve.create.sync();

console.log(resolve(process.cwd(), 'nanoid'));
```

And the stack trace is:

```
/Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/Resolver.js:246
		if (err) throw err;
		         ^

Error: Package path . is not exported from package /Users/pierre/dev/test-ntm-nanoid/node_modules/nanoid (see exports field in /Users/pierre/dev/test-ntm-nanoid/node_modules/nanoid/package.json)
    at /Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/ExportsFieldPlugin.js:104:7
    at Hook.eval [as callAsync] (eval at create (/Users/pierre/dev/test-ntm-nanoid/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pierre/dev/test-ntm-nanoid/node_modules/tapable/lib/Hook.js:18:14)
    at Resolver.doResolve (/Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/Resolver.js:407:16)
    at /Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:74:17
    at /Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:118:13
    at /Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at onJson (/Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:108:6)
    at /Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:68:7
    at SyncAsyncFileSystemDecorator.readJson (/Users/pierre/dev/test-ntm-nanoid/node_modules/enhanced-resolve/lib/SyncAsyncFileSystemDecorator.js:89:25)
```

`nanoid`'s `exports` field looks like this:

<img width="1030" alt="Screen Shot 2021-02-08 at 11 07 19" src="https://user-images.githubusercontent.com/1311607/107205213-de2c0000-69fd-11eb-9fe5-281ba0313956.png">

Any idea what could go wrong exactly? Am I misusing `enhanced-resolve`?

cheers!

**Comment by sokra** [comment]
There is no `default` condition in the exports field and you didn't specify any conditions in the resolver (`conditionNames` option)

**Comment by martpie** [comment]
Great, thank you! I will forward that to the maintainer of `nanoid`!

**Comment by sokra** [comment]
You need to pass the conditions that applies in your use case. E.g. `import` if this is a request from an `import`.

**Comment by martpie** [comment]
Thank you for the tip!

**Comment by ai** [comment]
@sokra what file we should use `default` export section?

**Comment by sokra** [comment]
Note that's not wrong to not have a `default`, we just recommend to have one as fallback for unforeseen and future cases.

Here is a note about that in our guide:
https://webpack.js.org/guides/package-exports/#common-patterns
Reading the whole guide is also interesting, but it's pretty long...

Anyway here you can change `imports` to `default`.

**Comment by ai** [comment]
I added `default` and `browser.default` to `dual-publish` and re-released Nano ID

https://github.com/ai/dual-publish/commit/a85c242d2348c999089625f0f125ccd650d89a40

**Comment by martpie** [comment]
Thank you very much @ai !
