### ISSUE TITLE
Question to resolve Node APIs

### ISSUE THREAD

**Issue by Nebulis** [webpack/enhanced-resolve#296]
Hi,

I tried to resolve a node API the following:
```
const resolver = require('enhanced-resolve').create.sync({
  conditionNames: ['require', 'node', 'default', 'import'], 
  extensions: ['.js', '.json', '.node', '.ts']
})
console.log(resolver(__dirname, "fs"))
```

It fails but I guess it's normal as it's a lib for webpack. However, I wondered if there is any config to make it easier to resolve node APIs? (fs, path, crypto)

**Comment by alexander-akait** [comment]
It is just resolver, we don't know what is Node.js module or user module
