### ISSUE TITLE
[Question] Support for nested conditions

### ISSUE THREAD

**Issue by scinos** [webpack/enhanced-resolve#302]
According to Node docs, [nested conditions](https://nodejs.org/api/packages.html#packages_nested_conditions) are valid.

Does `enhanced-resolve` support nested conditions?

**Comment by alexander-akait** [comment]
Yes

**Comment by scinos** [comment]
Would you mind explaining how? It is not obvious from the docs:

>  conditionNames | ["node"] | A list of exports field condition names

**Comment by alexander-akait** [comment]
We have `exportsFields` (`exports`) so `enhanced-resolve` also we have `conditionNames: ["require", "node"],` to understand them

**Comment by scinos** [comment]
Maybe I wasn't clear about what I mean by **nested** conditions, my apologies.

If I have an `exports` field like

```
 "exports": {
    "node": {
      "import": "./feature-node.mjs",
      "require": "./feature-node.cjs"
    },
    "import": "./feature.mjs",
    "require": "./feature.cjs",
  }
```

What do I need to pass in `conditionNames` to target `node.import` (i.e. get it resolved to `./feature-node.mjs`) first and `import` next (i.e. get `./feature.mjs`)?

**Comment by alexander-akait** [comment]
How you use `enhanced-resolve`?

**Comment by scinos** [comment]
```
const resolver = enhancedResolve.create.sync( {
	extensions: [ '.json', '.js', '.jsx', '.ts', '.tsx' ],
	mainFields: [ 'calypso:src', 'main' ],
	conditionNames: [ 'calypso:src', 'node', 'import' ],
} );

module.exports = function ( request, options ) {
	return resolver( options.basedir, request ).replace( /\0#/g, '#' );
}
```

That file is then requested by Jest as a custom resolver.

**Comment by alexander-akait** [comment]
`conditionNames: [ 'calypso:src', 'node', 'import' ],` you need put `require` here, what is the problem?

**Comment by scinos** [comment]
How do you express "Get me `node.require` or `import`, but don't give me `node.import`"?

**Comment by alexander-akait** [comment]
it doesn't work like that...

**Comment by scinos** [comment]
What doesn't work like that? Nested conditions in general? Or how `enhanced-resolve` solves them?

I'm writing a custom resolver for Jest using `enhanced-resolve`. I was planning to have a bunch of conditional exports in some our packages:

```
 "exports": {
    "calypso:src": {
      "require": "./dist/file.js",
      "import": "./file.js"
    }
  }
```

But some packages will just have
```
 "exports": {
    "require": "./dist/file.js",
    "import": "./file.js",
    "default": "./whatever.js"
}
```

The _same_ resolver has to resolve both cases. I need it to get `calypso:src/import` OR `require` OR `default`, but NOT `import`. And reading the doc for `enhanced-resolve` I didn't find any reference that nested imports are supported at all. Hence the original question.

Did I misunderstood what can be done with nested conditional exports? Docs in Node and https://webpack.js.org/guides/package-exports/#conditional-syntax seems to suggest it is possible. I just don't know how to express that requirement in a way that `enhanced-resolve` understands.

**Comment by alexander-akait** [comment]
You can't provide special condition names for special exports fields

**Comment by alexander-akait** [comment]
But you can solve it using two/three and more resolvers, just try to resolve using `calypso:src`, if not found, try to resolve `require` and `default`
