### ISSUE TITLE
`exports` and `node_modules` inside package resolving broken

### ISSUE THREAD

**Issue by alexander-akait** [webpack/enhanced-resolve#304]
@alexander-akait I think you closed my issue prematurely, though granted it was a bit inaccurate.

I've done a bit more digging - the key difference between the `node_modules` folders that npm and yarn generate is that yarn creates `node_module` folders in each dep where their deps have cli tools with a nested `.bin` folder and npm does not.

So from the above, `ipfs-unixfs-importer` depends on `rabin-wasm` which has a [cli tool](https://github.com/hugomrdias/rabin-wasm/blob/master/package.json#L11).

With npm I get:

```
my-project/
├── node_modules/
│   ├── .bin/
│   │   └── rabin-wasm
.. other files
│   ├── ipfs-unixfs-importer/
|   |   └── package.json // etc
```

With yarn I get:

```
my-project/
├── node_modules/
│   ├── .bin/
│   │   └── rabin-wasm
.. other files
│   ├── ipfs-unixfs-importer/
│   │   ├── node_modules/
│   │   │   └── .bin/
│   │   │       └── rabin-wasm
|   |   └── package.json // etc
```

If I remove (or rename) the nested `my-project/node_modules/ipfs-unixfs-importer/node_modules` folder everything works, if I leave it, webpack does not resolve the `rabin-wasm` dependency.  I guess it doesn't walk back up the tree to find the next `node_modules` folder if the first one doesn't have the dep it's looking for like node does?

You can see this yourself with the [repro repo](https://github.com/achingbrain/webpack-cjs-esm-yarn-npm).

_Originally posted by @achingbrain in https://github.com/webpack/webpack/discussions/14268#discussioncomment-1345976_

**Comment by alexander-akait** [comment]
@achingbrain we have a bug, somewhat critical

exports example:
```
"exports": {
    ".": {
      "browser": "./esm/src/index.js",
      "require": "./cjs/src/index.js",
      "import": "./esm/src/index.js"
    }
  }
```

Reproducible:
- we have `package node_modules/package-1`  with `node_modules` and the `exports` field
- we try to load `package-2`  inside `node_modules/package-1/index.js` 
- due `ModulesInHierachicDirectoriesPlugin` logic we try to search in `node_modules/package-1/node_modules/package-2` , (using - `request`  - `./package-2` and `path`  - `node_modules/package-1/node_modules`)
- `package-2` doesn't exist
- but because we apply `ExportsFieldPlugin` plugin we try to search in the `exports field and `./package-2` return `browser`  entry from the `exports` field

**Comment by alexander-akait** [comment]
Let's wait @sokra answer, fix is easy, we should skip resolving in `ExportsFieldPlugin` when we try to resolve file from `ModulesInHierachicDirectoriesPlugin`

**Comment by achingbrain** [comment]
I think this problem also exists for `enahnced-resolve@4.x.x`, is there any possibility a fix can be backported for those still using webpack 4 (e.g. react-scripts, etc)?

**Comment by alexander-akait** [comment]
@achingbrain i am afraid v4 accept only security fixes, what is the blocker to update?
