### ISSUE TITLE
Webpack does not seem to work with nodes subpath imports.

### ISSUE THREAD

**Issue by wpitallo** [webpack/enhanced-resolve#307]
# Bug report

Webpack does not seem to work with nodes subpath imports.

https://nodejs.org/api/packages.html#packages_subpath_imports

I have the following in my package.json

```
  "imports": {
    "#core/*": "./core/*.js",
    "#helpers": "./core/helpers/index.js",
    "#helpersSrc/*": "./core/helpers/src/*.js"
  },
```

If dont bundle so I just run with node it works. As soon as I try bundle with webpack I get:

Module not found: Error: Can't resolve '#core/controllers/_controller'

**What is the expected behavior?**

Webpack should resolve these the same way that node does.

**Other relevant information:**
webpack version:  5.36.2
Node.js version: v14.16.1
Operating System: Ubuntu
Additional tools: -

**Comment by sokra** [comment]
Please try with latest webpack and enhanced-reaolve version

**Comment by alexander-akait** [comment]
Feel free to feedback

**Comment by deakjahn** [comment]
@alexander-akait Any chance of a sample showing how to do it? I'd like to resolve `#common/foobar` as `./common/src/foobar.ts`, for instance. This is cleary not the way it should be done: :-)

    const EnhancedResolvePlugin = require("enhanced-resolve");
    EnhancedResolvePlugin.sync("#common/foobar", "./common/src/foobar.ts");

**Comment by alexander-akait** [comment]
@deakjahn You need to pass options...

**Comment by deakjahn** [comment]
Very nice. And the [documentation](https://github.com/webpack/enhanced-resolve#passing-options-from-webpack) doesn't show how and even referes to a different plugin. :-))
