### ISSUE TITLE
RootsPlugin causes watchpack watches a set of wrong paths

### ISSUE THREAD

**Issue by wood1986** [webpack/enhanced-resolve#311]
https://github.com/webpack/enhanced-resolve/blob/d1a3cb65cdf90754871a263172006e2902a2f86e/lib/RootsPlugin.js#L42

This gives a path `'/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web'` See the following screenshot

![image](https://user-images.githubusercontent.com/5212215/135038075-64af9754-a5ee-4762-8cd1-626850ca1521.png)

because of that, watchpack watches a set of wrong paths

https://github.com/webpack/watchpack/blob/c651129195d84cc80e547a45be38861b5bbada1a/lib/watchEventSource.js#L56

![image](https://user-images.githubusercontent.com/5212215/135039213-5b7ad543-d5b6-4230-907d-e546c4627216.png)

Is there a reason of coding this `resolver.join(root, req.slice(1));`? 

Here is the reproducible repo https://github.com/wood1986/rootplugin-bug
1. yarn
2. yarn start

**Comment by wood1986** [comment]
You can repro it any webpack project

**Comment by alexander-akait** [comment]
Expected, because you can have links

**Comment by wood1986** [comment]
Yes, I pass the entry but `webpack` and `enhanced-resolved` give this link '/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web'. I did not specify `roots` in my `weboack.config.js` and `webpack` will autofill `roots` with `context` which is the `__dirname`. I think this behaviour is wrong. 

If it is wrong to you, I do not know which party should fix it

**Comment by alexander-akait** [comment]
Bug in `unionfs`, some errors is not possible to ignore,  why you need this?

**Comment by alexander-akait** [comment]
`'/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web'` happens, because you can have:

`import foo from '/foo/bar.js';`

you can have `/foo/bar.js` as absolute path to file and as URL (`http://example.com/foo/bar`, i.e. relative to context), so we need to check both

**Comment by wood1986** [comment]
> Bug in `unionfs`, some errors is not possible to ignore, why you need this?

you are partially correct but `unionfs` is not the root cause. If I patch the fs, the `.on` is broken . If I do not patch it, the issue still exists and watchpack hide the legit error in the try catch block.

The reason of having this is I want to require a js output inside the `compiler.outputFileSystem`

Otherwise, I am going to do this on watchpack side `watcher.on && watcher.on()` and `watcher.close && watcher.close()`. But it is odd to me because this is not the root cause

**Comment by alexander-akait** [comment]
Can you clarify why you need to patch fs? Layer fs (i.e. in memory and on disk)? Why do you need error message?

**Comment by wood1986** [comment]
Because I am building a SSR plug-in which will bundle the js files for node to run. And the webpack middleware will require this file to output and return the html when using with webpack-dev-server.

I do not need this error message. Currently

**Comment by alexander-akait** [comment]
We have `writeToDisk` options for `webpack-dev-middleware`

**Comment by wood1986** [comment]
yes, but the web version js is able to output to memfs but node version js cannot. I expect a symmetric output

**Comment by alexander-akait** [comment]
Using your repo I don't got your problem, my problem is:
```
Watchpack Error (watcher): TypeError: watcher.on is not a function
/home/evilebottnawi/IdeaProjects/rootplugin-bugzz/node_modules/watchpack/lib/watchEventSource.js:75
                        if (this.watcher) this.watcher.close();
```

I really don't understand what you try to fix, also fix is invalid.

Also changing `fs` in `after` is wrong places, you should do it before webpack starts, otherwise if will have corrupted fs caches.

Why you patch `require`? Using `outputFileSystem` for `require` is fully unsafe

**Comment by wood1986** [comment]
> Why you patch require? Using outputFileSystem for require is fully unsafe

Before helping you to understand the issue, I want to say you should not care how I patchFs because it is not the main point. I find that patchFs exposes the hidden issue accidentally. Additionally, I am trying to expose the memfs for yarn pnp to require the file from the memfs. 

> Using your repo I don't got your problem, my problem is:

I have been telling you the problem you see is because RootsPlugin L42 generates the wrong path. You will only see the error after patching the fs. If there is no patchFs, you won't see it because watchpack hide the error but it does not mean it is valid.

Could you help me to understand why the path '/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web' is correct behavior and I did not specify 'roots', 'context' options in my webpack.config.js.

This path is generated from RootsPlugins L42 and watchpack will watch this invalid path based on the resolver result.

**Comment by alexander-akait** [comment]
> Could you help me to understand why the path /Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web is correct behavior and I did not specify 'roots', 'context' options in my webpack.config.js.

Because you can have `/foo/bar` as absolute path and set `context: '/foo/bar/'` and `require('/foo/bar')`, so `/foo/bar` and `/foo/bar/foo/bar/` are valid cases, and we should check them both, we can't check using `statsWiths`

I can't help you because I don't understand what you want archive. Do you want to use memfs for yarn? Sorry, I think it is not fully possible due limitations on yarn and webpack, webpack fs is fully design for webpack and it is not really like `fs` package (yes, it contains same methods).

**Comment by wood1986** [comment]
> > Could you help me to understand why the path /Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web is correct behavior and I did not specify 'roots', 'context' options in my webpack.config.js.
> 
> Because you can have `/foo/bar` as absolute path and set `context: '/foo/bar/'` and `require('/foo/bar/')`, so `/foo/bar` and `/foo/bar/foo/bar/` are valid cases, and we should check them both, we can't check using `statsWiths`, it will break resolutions logic
> 
> I can't help you because I don't understand what you want archive. Do you want to use memfs for yarn? Sorry, I think it is not fully possible due limitations on yarn and webpack, webpack fs is fully design for webpack and it is not really like `fs` package (yes, it contains same methods).

But I am not fixing the result of resolver.resolve

**Comment by alexander-akait** [comment]
You change `path`, so resolution will be different

**Comment by wood1986** [comment]
Yes the path in https://github.com/webpack/enhanced-resolve/blob/d1a3cb65cdf90754871a263172006e2902a2f86e/lib/RootsPlugin.js#L45

because path will be used by watchpack to watch the path

> I can't help you because I don't understand what you want archive. Do you want to use memfs for yarn? Sorry, I think it is not fully possible due limitations on yarn and webpack, webpack fs is fully design for webpack and it is not really like fs package (yes, it contains same methods).

please forget yarn as I have been saying the issue still exists without yarn and watchpack hide the error and I do not want to confuse you

**Comment by wood1986** [comment]
If enhanced-resolve wont fix it, the whole resolution still use the wrong path

**Comment by alexander-akait** [comment]
We hide errors, because it will be spammy to output ENOENT, again `enhanced-resolve` check many things and should watch them, for example you can have `resolver.extension: ['.jsx', '.js']` and we should watch `file.jsx` and `file.js`, otherwise we can't run compilation again on added files

**Comment by alexander-akait** [comment]
Sorry, you don't listen to me (I repeat the same things many times), I can't help you

**Comment by wood1986** [comment]
> We hide errors because it will be spammy to output ENOENT, again `enhanced-resolve` check many things and should watch them, for example you can have `resolver.extension: ['.jsx', '.js']` and we should watch `file.jsx` and `file.js`, otherwise we can't run compilation again on added files

I understand that that's why I think the root cause is in this package not watchpack. I can do watcher.on && watcher.on() and watcher.close && watcher.close() but this fix does not make sense

**Comment by wood1986** [comment]
> you don't listen to me 

Which part I don't listen? You are focusing on the result resolver.resolve and I am telling you wrong information `path` inside the request obj while resolving. Your example `/foo/bar/foo/bar/` will not be affected the result while resolving. I have showed you in my new test case of my PR and the result of resolver.resolve of the existing test cases are passed

> I can't help you

Do you know who can help me? Could you please help me one last thing adding the related people to this thread?

**Comment by alexander-akait** [comment]
What is the problem with resolving `/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web`?

**Comment by wood1986** [comment]
Thanks for coming back. Resolving this is not a problem `/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src/index.web` But this path lives inside request obj and then used by watchpack for the watch. The side effect of this path makes watchpack recusively watch the following dir

`/Users/wood/Desktop/webpack-bug/Users`
`/Users/wood/Desktop/webpack-bug/Users/wood`
`/Users/wood/Desktop/webpack-bug/Users/wood/Desktop`
`/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug`
...
`/Users/wood/Desktop/webpack-bug/Users/wood/Desktop/webpack-bug/examples/relay/src`

This is the issue

**Comment by alexander-akait** [comment]
Yes, as I said before it is expected, even more `enhanced-resolve` can have plugins and watch more things

**Comment by wood1986** [comment]
If you still think it is expected even with the path inside request obj 
![image](https://user-images.githubusercontent.com/5212215/135725541-331cb199-32a5-442f-9be2-4036f7586f56.png)

Then I cannot continue.

Now the discussion will be on watchpack side. May I request adding `watcher.close && watcher.close()` and `watcher.on && watcher.on()` in this `watchEventSource.js`? (I know this should be discussed on watchpack side)

Otherwise, I do not know how to fix my plugin without asking consumer using `writeToDisk` options
