### ISSUE TITLE
Problem with exports

### ISSUE THREAD

**Issue by pauldraper** [webpack/enhanced-resolve#313]
I'm not sure what the nature of the problem is, but the `@rollup/pluginutils` package won't resolve.

```sh
npm init
npm i @rollup/pluginutils@3.1.0
```

Node.js succeeds:

```js
require.resolve('@rollup/pluginutils');
```

> .../node_modules/@rollup/pluginutils/dist/cjs/index.js

enhanced-require fails:

```js
require('enhanced-resolve').sync(process.cwd(), '@rollup/pluginutils');
```

> Error: Package path . is not exported from package .../node_modules/@rollup/pluginutils (see exports field in .../node_modules/@rollup/pluginutils/package.json)

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
