### ISSUE TITLE
Support typescript@4.5 `.js` import extension requirement

### ISSUE THREAD

**Issue by vjpr** [webpack/enhanced-resolve#317]
ESM requires all relative imports to use an extension. TS requires insists on using `.js` inside `.ts` files which is left untouched in the output file.

See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html

> relative import paths need to use extensions

> When a .ts file is compiled as an ES module, ECMAScript import/export syntax is left alone in the .js output

> As a result, it will have to be rewritten to use the extension of the output of foo.ts - so bar.ts will instead have to import from ./foo.js.

---

When trying to resolve `#src/index.js` from a TypeScript file, it should search for `#src/index.ts`. The extension needs to be stripped during search.

I use this for transpilation on-the-fly.

Would be nice to have a setting to accomplish this.

## Workaround

I could just remove '.js' extensions before passing them to `enhanced-resolve`.

**Comment by alexander-akait** [comment]
We have options and plugins, you can do it using them, it should be done in `ts-loader`

**Comment by vjpr** [comment]
I am actually using it in an `node --experimental-loader` hook. Currently I am planning to just chop off `.js` extensions, but then there is a perf impact if I chop off the extension and then it must search all extension.

> We have options

Is there an option I am missing that handles this?

**Comment by alexander-akait** [comment]
You see this https://github.com/TypeStrong/ts-loader/issues/1383

**Comment by vjpr** [comment]
Thanks, this logic is TS-specific so should not be inside enhanced-resolve as you mention.
