### ISSUE TITLE
Exports and `conditionNames` matching

### ISSUE THREAD

**Issue by niksy** [webpack/enhanced-resolve#318]
I have a question regarding resolving with `exports` field and `conditionNames`.

I have following custom resolver options:

```js
const options = {
  extensions: [".scss", ".css"],
  conditionNames: ["sass", "style", "browser", "import", "require", "node"],
  mainFiles: ["_index", "index"],
  mainFields: ["style", "browser", "module", "main"],
  modules: ["node_modules"],
};
```

My package in `node_modules` has this `package.json`

```json
{
	"exports": {
		".": {
			"import": "./index.js",
			"style": "./index.css"
		}
	},
	"style": "index.css"
}
```

With this configuration package is still resolved to `index.js` instead of `index.css` even though `exports.style` field is defined earlier than `exports.import` field. If  I remove `exports.import` field, or if I remove extension, file is properly resolved to `index.css`.

Is this normal behavior? I was expecting that `conditionNames` field is resolved when first item matches (in this case, this should be `style`).

**Comment by niksy** [comment]
OK, I’ve remembered following [note from official documentation](https://nodejs.org/api/packages.html#:~:text=Within%20the%20%22exports%22%20object%2C%20key%20order%20is%20significant.%20During%20condition%20matching%2C%20earlier%20entries%20have%20higher%20priority%20and%20take%20precedence%20over%20later%20entries.%20The%20general%20rule%20is%20that%20conditions%20should%20be%20from%20most%20specific%20to%20least%20specific%20in%20object%20order.):

> Within the [`"exports"`](#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. _The general rule is that conditions should be from most specific to least specific in object order_.

If I put `style` before `import`, everything works. Is that OK?

**Comment by alexander-akait** [comment]
Please provide reproducible example

**Comment by sokra** [comment]
There is no order in `conditionNames`.

The matching order is given by the order of the properties in the `"exports"` field.
