### ISSUE TITLE
Slow module resolution with several `modules` folders

### ISSUE THREAD

**Issue by s-panferov** [webpack/enhanced-resolve#32]
Hi @sokra,

I faced with strange issue with _very_ slow build and debugging showed that if I add several folder to `modules`, webpack will search in **every** additional folder **several times** even when target module can be found in the first folder. Is this behavior desired?

How to debug:

```
resolve: {
    modules: ['node_modules', '/folder1', '/folder2']
}
```

then add console.log here: https://github.com/webpack/enhanced-resolve/blob/master/lib/ModulesInRootPlugin.js#L23

```
do resolve /folder1 revjet-csp-data/src/Ontology.js
do resolve /folder2 revjet-csp-data/src/Ontology.js
do resolve /folder1 revjet-csp-data/src/Ontology.js
do resolve /folder2 revjet-csp-data/src/Ontology.js
```

And it seems like it grows in `n^2` manner. For one folder there are two resolves, for two folders - 4 resolves.

**Comment by mikesherov** [comment]
Thanks for contributing! I can not replicate this behavior using the provided information. Please feel free to reply to this thread with more information, and I'll gladly reopen it!
