### ISSUE TITLE
[help request]

### ISSUE THREAD

**Issue by mistercoffee66** [webpack/enhanced-resolve#330]
In the [docs](https://github.com/webpack/enhanced-resolve#readme), we have the following example:

```
class MyResolverPlugin {
	constructor(source, target) {
		this.source = source;
		this.target = target;
	}

	apply(resolver) {
		const target = resolver.ensureHook(this.target);
		resolver
			.getHook(this.source)
			.tapAsync("MyResolverPlugin", (request, resolveContext, callback) => {
				// Any logic you need to create a new `request` can go here
				resolver.doResolve(target, request, null, resolveContext, callback);
			});
	}
}
```

and then a sample webpack config:

```
resolve: {
  extensions: ['.js', '.jsx'],
  modules: [path.resolve(__dirname, 'src'), 'node_modules'],
  plugins: [new DirectoryNamedWebpackPlugin()] // i have changed this to MyResolverPlugin to match the above class
  ...
},
```

In this example, what are the `source` and `target` args passed to the constructor? They come up as `undefined` for me. Using 
`"webpack": "^5.69.0"` 

Thanks!

**Comment by vankop** [comment]
So here is "pipeline" of resolving https://github.com/webpack/enhanced-resolve/blob/main/lib/ResolverFactory.js#L281 

`source` should be a hook name which you want to tap like here https://github.com/webpack/enhanced-resolve/blob/main/lib/ResolverFactory.js#L345 
and `target` is next hook in pipeline

**Comment by mistercoffee66** [comment]
@vankop Thanks for the quick response. I did see that before, but somehow the lightbulb went off when you wrote it. Cheers!
