### ISSUE TITLE
Is it possible to find the "first" issuer of a `request`?

### ISSUE THREAD

**Issue by clauderic** [webpack/enhanced-resolve#332]
I'd like to know if it's possible to find the first issuer of a `request`, for example:

```js
// ./app/App.js
import {A} from 'a';
```

When processing the request for 'a', its issuer is `./app/App.js`. If the resolver makes subsequent requests within `'a'`, is it possible to keep track of the original issuer? Or is this simply not possible at the resolver level?

For example, when resolving the request to `'b'` within `'a'`, can we know that the first issuer that initiated the chain of requests was `./app/App.js`?
```js
// 'a'
import B from 'b';
```

**Comment by vankop** [comment]
sorry, right now there is no way to do this.
