### ISSUE TITLE
About the new change in AliasPlugin.js

### ISSUE THREAD

**Issue by MMMarcinho** [webpack/enhanced-resolve#334]
last week, your team update the version of the enhanced-resolve
however, using v5.9.2, my project cannot build at all, it will be stuck while building. 
It makes me really puzzled, because my project's alias is `'#': path.resolve(__dirname, './src'),`
when I change it into `'balabala': path.resolve(__dirname, './src'),`, it will continue to build. balabala can be anything but #
and when I change the line 47 into "request.path",  `'#': path.resolve(__dirname, './src'),` can also make it.
So I'm wondering the reason why your team make such a change

**Comment by vankop** [comment]
hm.. not sure that `#` as request is valid one..

**Comment by MMMarcinho** [comment]
> 

Now I make it clear the reason why it stops building.
Maybe the line 48 is not rigorous enough. If the alias is `'<Single Character>': path.resolve( .....)`, and then, after slice(0, -1), single character will be **''** , and `.startsWith('')` will return true in any cases.
Not using `.slice(0, -1)` for the single string might be the better option?

**Comment by vankop** [comment]
I'll take a look. this should be fixed..
