### ISSUE TITLE
why `.mjs` import a different file with other in webpack4

### ISSUE THREAD

**Issue by VisonM** [webpack/enhanced-resolve#338]
### reproduce link
 https://github.com/VisonM/import-mjs-reproduce-webpack4
 
 ### screenshot
![image](https://user-images.githubusercontent.com/40595135/159199943-d365c242-e337-4c6b-bdf0-35109043e5ec.png)

### introduction

`webpack version:4.46.0`
`enhanced-resolve version:4.5.0`

I use [`vue-i18n-composable`](https://github.com/intlify/vue-i18n-composable) in a web project base on [`@vue/composition-api`](https://github.com/vuejs/composition-api)

```js
// a simple vue component

/*  this file import @vue/composition-api
* but it resolve result node_modules/@vue/composition-api/dist/vue-composition-api.mjs  this is correct🌈
*/
import {computed} from "@vue/composition-api"; 
```

```
// vue-i18n-composable/package.json
{
   "module": "dist/index.mjs" // it will use this field when we import vue-i18n-composable in webpack build
}
```

```js
// vue-i18n-composable/dist/index.mjs

/*  this file import @vue/composition-api
* but it resolve result is node_modules/@vue/composition-api/index.js,this is wrong❌
*/
import {computed, getCurrentInstance} from "@vue/composition-api"; 
```

more detail in this pr https://github.com/intlify/vue-i18n-composable/pull/15

However,I can't reproduct in webpack2 and webpack5.

### my question
* Is this a webpack4 bug?
* Will webpack handle files with `.mjs` suffix specially?
* what caused this problem
* Based on webpack4 how should I solve it

**Comment by vankop** [comment]
not sure that webpack@4 supports `mjs` by default. please add `.mjs` to extensions settings https://webpack.js.org/configuration/resolve/#resolveextensions

**Comment by VisonM** [comment]
vuecli has add .mjs to extensions
![image](https://user-images.githubusercontent.com/40595135/159208399-e8a66982-a40f-4c60-aebc-5bfa40deb86b.png)

also obviously it has loaded an mjs file(@vue/composition-api/dist/vue-composition-api.mjs),it support `mjs` 

![image](https://user-images.githubusercontent.com/40595135/159208660-a7cbc1b5-1948-448a-8765-cadc99f663b7.png)

**Comment by vankop** [comment]
I can't help with `vue-cli` setting, I just describing how to make webpack work with `.mjs` extension.

**Comment by VisonM** [comment]
@vankop 
I mean, I have configured mjs extension in webpack4. But he still works abnormally. The exception is that it does not always import files of the same module type, maybe my expression is not clear enough.

**Comment by vankop** [comment]
which version of `@vue/composition-api` ?

**Comment by vankop** [comment]
ok I see.. Unfortunately, this is unsolvable for webpack@4 ( it does not support `exports` field ). please use direct import for `.mjs` then..

**Comment by VisonM** [comment]
ok, thanks for your patience.but I'm still a little suspicious.
You mean @vue/composition-api/package.json has exports field
```
"exports": {
    ".": {
      "import": "./dist/vue-composition-api.mjs",
      "require": "./index.js"
    },
    "./*": "./*"
  },
```
when we use require, it will point to "require": "./index.js"?
 
 but i always use `import` how did he become `require`? because babel transforms the module?
