### ISSUE TITLE
resourceQuery appending to package from node_modules result to wrong module request

### ISSUE THREAD

**Issue by huozhi** [webpack/enhanced-resolve#339]
### Description

Adding resourceQuery seems doesn't work for packages in node_modules

### Observed 

For instance, adding a resource query `myquery` to the import declaration such as `import Foo from 'foo'` will become `import Foo from 'foo?myquery' `. The final package is resolved as ./?myquery

The logic seems from https://github.com/webpack/enhanced-resolve/blob/e5ff68aef5ab43b8197e864181eda3912957c526/lib/ExportsFieldPlugin.js#L55-L60

### Expected

The resolved module request is still `foo` and webpack loader could capture resource query `myquery`

**Comment by vankop** [comment]
hm.. I will take a look.

**Comment by vankop** [comment]
here webpack has parity with Node.js 
<img width="750" alt="Screenshot 2022-03-25 at 11 42 46" src="https://user-images.githubusercontent.com/10380560/160086028-e7bdaee1-0560-435a-b7e8-9425a349bb48.png">

foo/package.json
```json
{
  "name": "foo",
  "version": "1.0.0",
  "exports": {
    ".": "./a.js"
  }
}
```

**Comment by vankop** [comment]
I agree that this restriction could be kind of weird.. but this is how `exports` field works. in case
```
"exports": { "X": "Y" }
```
`X` is subpath of specifier (`<specifier>/<subpath>`) and then `X` is compared to `<subpath>` by string comparison.
so symbols like `?`/`#` a considered as part of `<subpath>`

**Comment by huozhi** [comment]
Thanks for clarafication! So sounds like I shouldn't use the resourceQuery for 3rd party packages. Will try other approaches to achieve it since we just wanna apply some loaders to it. 🙏
