### ISSUE TITLE
When package xxx supports 'exports' and 'types', 'xxx/types' import leads an error

### ISSUE THREAD

**Issue by ooyyloo** [webpack/enhanced-resolve#341]
Hey, I'm using "enhanced-resolve" recently. When I use it to resolve "react-easy-crop/types", an error occurs. It says 

        Package path ./types is not exported from package zzz/nodemodules/react-easy-crop (see exports field in zzz/nodemodules/react-easy-crop/package.json)

It seems that this error message is thrown by certain plugin in ResolverFactory.js, as I delete the "exports" field, "react-easy-crop/types" can be resolved.

What's more, when I try to create a resolver by myself, I found that the Resolve class is abstract...

I don't know how to resolve "react-easy-crop/types" using "enhanced-resolve". Could you give me some advices?

**Comment by vankop** [comment]
`exports` field defines package exports. In your case if there is no `./types` entry in exports, it means that package author think that `./types` are internal module and should not be exported..

**Comment by vankop** [comment]
If you think that this is export bug please report it to package author
