### ISSUE TITLE
[Question] The behavior of importsField conflicts with `require.resolve`

### ISSUE THREAD

**Issue by bvanjoi** [webpack/enhanced-resolve#346]
For the [out of package scope of importField](https://github.com/webpack/enhanced-resolve/blob/main/test/importsField.js#L1214) example, there are some inconsistencies between `require.resolve` and `enhanced-resolve`.

Executing `require.resolve('#b')` in the importsField folder will report an error directly:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/30187863/169676352-db069fd3-c1d2-4c88-a508-eb194f681a3b.png">

> node version: 12.22.10

But the above test case is executed normally.

So, should we add [checkTarget](https://github.com/webpack/enhanced-resolve/blob/main/lib/util/path.js#L195) logic to importsField as well?

**Comment by vankop** [comment]
hm.. how Node.js behave in this example? we should have parity with Node.js resolve algorithm here

**Comment by bvanjoi** [comment]
> hm.. how Node.js behave in this example? we should have parity with Node.js resolve algorithm here

Throw an error 😢

**Comment by vankop** [comment]
same error? I mean that it is not defined in `importsField` ?

**Comment by vankop** [comment]
in your example you have  `importsField` target out of package scope.
target - is right side of `importsField` ( in your example `../a.js`). Target is scoped to current package.json location, e.g. if you have 
```
a/
  package.json
```
you can't request target out of `a/` directory

**Comment by vankop** [comment]
it looks like `enhanced-resolve` doesn't throw error, lets fix it
