### ISSUE TITLE
New resolve mechanism breaks directory named plugin

### ISSUE THREAD

**Issue by sebastiandeutsch** [webpack/enhanced-resolve#35]
I'm trying to use the [directory-named-webpack-plugin](https://github.com/shaketbaby/directory-named-webpack-plugin/) with `webpack 2.1.0-beta.20`, but unfortunately it breaks. It seems that some internals have changed: `request.request` and `this.forEachBail` are both `undefined`. I've gotten pretty far by adapting the [CloneBasenamePlugin](https://github.com/webpack/enhanced-resolve/blob/master/lib/CloneBasenamePlugin.js).

I've created an [issue](https://github.com/shaketbaby/directory-named-webpack-plugin/issues/2) to document my findings.

Questions:

1) Is the plugin needed or can I do everything using `CloneBasenamePlugin`?
2) Is there any documentation how to create a directory resolver like this?

**Comment by sokra** [comment]
yep, closing as you already forked it

**Comment by sebastiandeutsch** [comment]
:-) no problem. For someone who comes here from Google a version that works with Webpack 2.x can be found [here](https://github.com/sebastiandeutsch/component-directory-webpack-plugin).
