### ISSUE TITLE
Memoize calls to memory-fs join for performance

### ISSUE THREAD

**Issue by wcjordan** [webpack/enhanced-resolve#36]
Calls to Resolver normalize can take up 5% to 8% of the build time.  If we memoize these calls we can improve webpack build performance.  Memoizing the join call seems to be the best place to intercept calls to memory-fs.  I'll put up a PR if this sounds reasonable.

Before
<img width="475" alt="before" src="https://cloud.githubusercontent.com/assets/1034455/17686918/8b03471e-633e-11e6-9af4-30a6a80de337.png">
After
<img width="432" alt="after" src="https://cloud.githubusercontent.com/assets/1034455/17686924/9282ca96-633e-11e6-93d0-729204a95a2b.png">

**Comment by sokra** [comment]
Thanks
