### ISSUE TITLE
add type defines for `CachedInputFileSystem` ?

### ISSUE THREAD

**Issue by PupilTong** [webpack/enhanced-resolve#367]
Background:

I'm using `enhanced-resolve` in language-server extension. 
To support Monaco/ webIDE, we cannot assume it has a node runtime. This means the `fs` may be not available.

Expection:
add type defines for the first argument of `CachedInputFileSystem`  constructor.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by PupilTong** [comment]
> ~PR welcome~ we have types https://github.com/webpack/enhanced-resolve/blob/main/types.d.ts#L27 what is the problem?

https://github.com/webpack/enhanced-resolve/blob/ca76a47f51b80d08f17dbc7a79b47161a43584c2/types.d.ts#L28

the first argument of constructor has `any` type

**Comment by alexander-akait** [comment]
I see, PR welcome, looks like just not finished

**Comment by PupilTong** [comment]
> I see, PR welcome, looks like just not finished

I tried to pass a object implemented `FileSystem` interface, and it works. 

Can I just update the code as
`constructor(fileSystem?: FileSystem, duration?: number); `?

**Comment by alexander-akait** [comment]
Yes
