### ISSUE TITLE
 signature of method `stat` in interface `FileSystem` mismatches.

### ISSUE THREAD

**Issue by PupilTong** [webpack/enhanced-resolve#369]
https://github.com/webpack/enhanced-resolve/blob/ca76a47f51b80d08f17dbc7a79b47161a43584c2/types.d.ts#L39-L46

The callback of the first overload has a argument of type `FileSystemCallback<FileSystemStats>`

However In the second overload, the callback accepts `FileSystemCallback<string | Buffer>`

Seems it uses string/Buffer to pass the stat info to callback. Any document about the format of the string/ Buffer?

**Comment by PupilTong** [comment]
Seems it is fixed on `5.11.0` but the pr is reverted.

**Comment by alexander-akait** [comment]
Just update `graceful-fs` and regenerate types, it should help, PR welcome
