### ISSUE TITLE
is this possible with webpack AliasPlugin to automatically switch to a different alias when original file is deleted?

### ISSUE THREAD

**Issue by latel** [webpack/enhanced-resolve#375]
is it possible, if both folder src/servers/overrides/server and Proto/ProtoCPP/HEAD/Proto/server have same file ABC.ts, when I delete src/servers/overrides/server/ABC.ts, webpack automatically use Proto/ProtoCPP/HEAD/Proto/server/ABC.ts

```
configureWebpack: {
        resolve: {
            plugins: [
                // @see https://github.com/webpack/webpack/issues/6817#issuecomment-542448438
                new AliasPlugin(
                    'described-resolve',
                    [
                        {
                            name: '%',
                            alias: [resolve('src/servers/overrides'), resolve('Proto/ProtoCPP/HEAD/Proto')],
                        },
                    ],
                    'resolve'
                ),
            ],
        },
    },
```

currently when I delete src/servers/overrides/server/ABC.ts, webpack throws ENOENT errors like this
![image](https://user-images.githubusercontent.com/5621862/228796965-c757e600-4283-4923-893e-701c5d0cee86.png)

**Comment by alexander-akait** [comment]
I think you are looking at https://webpack.js.org/configuration/resolve/#resolveroots

**Comment by latel** [comment]
> I think you are looking for https://webpack.js.org/configuration/resolve/#resolveroots

It's not, the main purpose is to use alias to remove relative paths. reolsve.roots cannot solve this kind of problem. I try to make my senario more I clear.

I've folders structure below
```
/path/to/proj/src/servers/overrides/server
/path/to/proj/Proto/server
```
I've ABC.ts in both folders
```
/path/to/proj/src/servers/overrides/server/ABC.ts
/path/to/proj/Proto/server/ABC.ts
```

I've webpack configs
```
...
const resolve = dir => path.join(__dirname, dir)
...
configureWebpack: {
        resolve: {
            plugins: [
                // @see https://github.com/webpack/webpack/issues/6817#issuecomment-542448438
                new AliasPlugin(
                    'described-resolve',
                    [
                        {
                            name: '%',
                            alias: [resolve('src/servers/overrides'), resolve('Proto')],
                        },
                    ],
                    'resolve'
                ),
            ],
        },
    }
}
...
```

I've codes
```
import ABC from '%/server/ABC';
ABC();
```

now, when I delete `/path/to/proj/src/servers/overrides/server/ABC.ts`, webpack will not re-locate ABC to `Proto/server/ABC.ts` but throw errors, says `/path/to/proj/src/servers/overrides/server/ABC.ts` not exists

**Comment by latel** [comment]
Actually, chatGPT understands loll, words from chatGPT:

> Unfortunately, this is not possible with webpack's default behavior. When resolving aliases, webpack will always prioritize the first matching alias it finds in the list, and will not automatically switch to a different alias if the original file is deleted.
> One possible workaround is to use a custom plugin that listens for file changes and updates the alias configuration accordingly. However, this would require significant development effort and may not be practical for your use case.
Alternatively, you could consider restructuring your code to avoid duplicate file names and aliases, or use a different tool that supports more advanced file resolution strategies.

**Comment by alexander-akait** [comment]
@latel Yeah, it is impossible, you can try `roots` + `alias` and it should work, but using only `AliasPlugin`

**Comment by zecka** [comment]
@latel I think my issue #395  is exactly the same than yours.
Did you find a solution ?

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/enhanced-resolve/issues/250, anyway PR welcome
