### ISSUE TITLE
Seeing "Error: No file content" for different package.json files when webpack rebuilds

### ISSUE THREAD

**Issue by agravell047** [webpack/enhanced-resolve#398]
Node: 14.15.0
Webpack: 5.76.0

Webpack appears to build my content fine. If I make more than a few changes, even as simple as a text change, webpack throws a continous loop of errors for unrelated node_modules folders' package.json file. The error shows as "Error: No file content" and points to random package json files as being the cause. I have traced the error back to this package that is throwing the error.

**Comment by alexander-akait** [comment]
Sorry, somethings wrong with your enviroment, I want to close this issue, but if it is still valid please create reproducible test repo and I will help you to fix it, thank you
