### ISSUE TITLE
Query not passed in aliased loader

### ISSUE THREAD

**Issue by IgnusG** [webpack/enhanced-resolve#41]
I'm getting the same unexpected behavior as in https://github.com/webpack/webpack/issues/1289. Aliased loaders do not receive query parameters. I checked the code and it seems the fix that was used before wasn't migrated with the new versions.

_Node: v5.12.0_
_webpack: 1.13.2_

**Comment by spalger** [comment]
@sokra the fix for this is really simple, but fixing it in webpack 1.x will require either releasing a patch for 0.9 or upgrading webpack 1.x to use the latest enhanced-resolve. Thoughts? 

I'm happy to submit the fix but need a target branch to point to
