### ISSUE TITLE
Ignore `Default condition should be last one`

### ISSUE THREAD

**Issue by scagood** [webpack/enhanced-resolve#421]
I am looking for a way to more closely mimic the nodejs resolution as in both https://github.com/eslint-community/eslint-plugin-n/issues/182 and https://github.com/eslint-community/eslint-plugin-n/issues/242 we have packages that don't correctly implement the exports order. However, they do resolve correctly when called in either `import` or `require`.

When debugging this initially I discoved the error was throw here: https://github.com/webpack/enhanced-resolve/blob/main/lib/util/entrypoints.js#L474-L476

What I am hoping for is that we can (via a passed in option) disable the throw?

---

I am very willing to submit code if that would help!

**Comment by alexander-akait** [comment]
> I am looking for a way to more closely mimic the nodejs resolution as in both https://github.com/eslint-community/eslint-plugin-n/issues/182 and https://github.com/eslint-community/eslint-plugin-n/issues/242 we have packages that don't correctly implement the exports order. However, they do resolve correctly when called in either import or require.

Can you provide an example, I want to investigate, thank you

**Comment by alexander-akait** [comment]
@scagood I see, let's change the logic and will be align with Node.js, just remove it our `throw new Error(...)`, we are not linter (although we throw errors about some critical things), but Node.js don't do it, so we will do the same,  do you want to send a PR?

**Comment by scagood** [comment]
:tada: Thank you @alexander-akait!
