### ISSUE TITLE
Should purge() clear _readJsonStorage?

### ISSUE THREAD

**Issue by sthzg** [webpack/enhanced-resolve#43]
By trying to solve [this problem](http://stackoverflow.com/questions/39428200/webpack-plugin-readjson-after-inputfilesystem-purge) I realized that invoking [`purge()`](https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js#L171) 

``` js
CachedInputFileSystem.prototype.purge = function(what) {
    this._statStorage.purge(what);
    this._readdirStorage.purge(what);
    this._readFileStorage.purge(what);
    this._readlinkStorage.purge(what);
}
```

does not clear `_readJsonStorage` and just wanted to confirm if this is intended or not.

**Comment by sokra** [comment]
Yes it should. Do you want to do a PR?

**Comment by sthzg** [comment]
@sokra absolutely. not sure I will get to it this weekend, if not I will submit a PR at the beginning of the next week.

**Comment by nowells** [comment]
This appears to have been fixed in https://github.com/webpack/enhanced-resolve/commit/3f3f4cd1fcbafa1e98c3c6470fed1277817ed607. Close?

**Comment by mikesherov** [comment]
Yes, this is fixed. Thanks!
