### ISSUE TITLE
Would you consider exposing a sync resolve function?

### ISSUE THREAD

**Issue by johnnyreilly** [webpack/enhanced-resolve#46]
Both [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/paths-plugin.ts) and [ts-loader](https://github.com/TypeStrong/ts-loader/blob/944d9c2254efef5c947d06eecc61acd84c72379d/resolver.ts) are presently rolling their own sync resolver functions.  It'd be great to get official support for this directly.  Is that something you'd consider supporting?  I suspect there may well be others out there similarly implementing this by hand as well.

cc @jbrantly @s-panferov

**Comment by niieani** [comment]
If possible, it would be useful for my webpack dependency suite too. Would be especially useful if the sync resolve function could return cached values from the async resolve if the FS is async in the calling context.

**Comment by johnnyreilly** [comment]
So it turns out this is catered for; just not really documented.  I've written a blog post about it [here](http://blog.johnnyreilly.com/2016/12/webpack-syncing-enhanced-resolve.html).  The TL;DR; show me an example is:

```js
const node = require("enhanced-resolve/lib/node");

function makeSyncResolver(options) {
    return node.create.sync(options.resolve);
}

const resolveSync = makeSyncResolver(loader.options);

const resolvedFileName = resolveSync(
    undefined,
    'C:\source\ts-loader\.test\babel-issue92',
    './submodule/submodule'
);

// resolvedFileName: C:\source\ts-loader\.test\babel-issue92\submodule\submodule.tsx
```

**Comment by niieani** [comment]
@johnnyreilly Would this work with a custom `fs` though?

**Comment by johnnyreilly** [comment]
I haven't tried - have a go!

**Comment by mikesherov** [comment]
@johnnyreilly please feel free to open a PR to the documentation of this repo (the README) describe this sync resolver. In the meantime, I'm going to consider this issue closed. Thanks!
