### ISSUE TITLE
npm link / potential memory leak issue

### ISSUE THREAD

**Issue by johnnyreilly** [webpack/enhanced-resolve#55]
@pelotom reported an issue when using ts-loader (which uses enhanced-resolve).  Details here: https://github.com/TypeStrong/ts-loader/issues/420#issuecomment-269446005

As you can see, @pelotom has now found a workaround and so isn't looking at this anymore.  This is not my issue but I wanted there to be some visibility of a potential problem in case it's something that merits attention.

**Comment by mikesherov** [comment]
Thanks for contributing @johnnyreilly. Do you have a simplified reproduction case for this issue? If so, we can take a look.

**Comment by mikesherov** [comment]
@johnnyreilly I'm going to close this for now, but if you can get a repro case going, and respond to this issue with it, I'll gladly reopen. Thanks!
