### ISSUE TITLE
ES6 Translations

### ISSUE THREAD

**Issue by nicosesma** [webpack/enhanced-resolve#59]
Tried to update some of the files to ES6 and encountered some linting errors while doing so. Is this happening because this project supports an older version of node or is it due to the configuration for eslint? @sokra would you mind clarifying this issue or pointing me towards the correct direction.

**Comment by mikesherov** [comment]
Just configuration. Any PR to bring es6 support needs to update the eslintrc with `es6: true`. Let me know if you have further questions, but closing for now, thanks!
