### ISSUE TITLE
Why process commented line?

### ISSUE THREAD

**Issue by klihelp** [webpack/enhanced-resolve#73]
On Build, Why processing commented line?
```
ERROR in ./src/app/app.routes.ts 
Module build failed: Error: Can't resolve './+barrel' in
at onResolved (../node_modules/enhanced-resolve/lib/Resolver.js:66:16)
```

 ```
 // app.routes.ts  
 // Comments
 //  { path: 'barrel', loadChildren: './+barrel#BarrelModule'},
```

ps - Using latest version3+. 

Similar issue in angular aot build: Cannot determine the module for class 
https://github.com/angular/angular/issues/13590

Potentially on ng-router-loader:
https://github.com/shlomiassaf/ng-router-loader/issues/3

**Comment by klihelp** [comment]
Update on this?

**Comment by mikesherov** [comment]
Hi @klihelp thanks for contributing! Can you please provide a minimal repro case showing this bug, as I don't believe it's in enhanced-resolve.

**Comment by mikesherov** [comment]
Yeah, this has nothing to do with enhanced-resolve, I'm pretty sure. Closing for now. If you have a minimal repro showing it's somehow related, please post it and I'll gladly reopen, thanks!

**Comment by klihelp** [comment]
thanks, have to research, maybe some webpack plugin is passing forward the //commented lines ..
