### ISSUE TITLE
Added node 4.x dependency in 3.1

### ISSUE THREAD

**Issue by jorupp** [webpack/enhanced-resolve#76]
Some people are still using an old version of node with webpack 1.13.0 and ts-loader 1.3.3, but ts-loader 1.3.3 references enhanced-resolve ^3.0.0, which now breaks with 3.1 requiring a newer version of node.

Shouldn't the added dependency make this 4.0?

**Comment by vutran** [comment]
Also am experiencing this issue with one of our legacy software.

**Comment by bebraw** [comment]
@TheLarkInn Node version bump should have probably been a new major version. I'm not sure what to do with the 3.x series (the cat is already out of the bag).

**Comment by vutran** [comment]
@bebraw @TheLarkInn I believe the last working version is `v3.0.3`. Current master should be published as `v4` since it has been rewritten since under ES6 and leave `v3` for legacy node versions.

**Comment by bebraw** [comment]
@vutran Yeah, fair point. I agree with the major bump.

**Comment by mikesherov** [comment]
There is really no way to resolve this in `enhanced-resolve`. As mentioned, the cat is already out of the bag: We can't publish another minor version of 3 that reverts functionality, and publishing a major version of `enhanced-resolve` won't fix the issue.

The only correct workaround at this point is to have `ts-loader` pin to `~3.0.0`, and only bump to `^3.0.0` when they are ready to do a major bump themselves.

Closing this issue for now, and will open a PR in ts-loader to pin to `3.0.3`. If anyone feels this is in error, please reply to this issue, and I'll re-open for further discussion.

**Comment by mikesherov** [comment]
Hmmm, this can't be fixed in ts-loader either, as they also now express a dependency on Node 4. 

The last thing you can do is put `enhanced-resolve: 3.0.3` as a dependency in your top level project, which will then, once deduped, have ts-loader using `enhanced-resolve: 3.0.3` and will work around the issue. Yes, it's a bit ugly, but it's all we can do at this point.
