### ISSUE TITLE
Resolve multiple files with a single require

### ISSUE THREAD

**Issue by linaspasv** [webpack/enhanced-resolve#80]
I am working on a bower support plugin where I would like to resolve multiple files once a single require being called. 

Lets say I do `` require('bootstrap') `` and this should include multiple files:

 ```js
var mainModules = [
     'dist/js/bootstrap.js',
     'less/bootstrap.less'
];
 ```

Here is my test code:

```js
    resolver.plugin('existing-directory', function (request, callback) {
        var mainModules = [];

        try {
            var source = require(path.resolve(request.path, 'bower.json'));
            mainModules = typeof source['main'] == 'string'
                ? [source['main']]
                : source['main'];
        } catch (e) {}

        if (mainModules.length == 0) {
            return callback();
        }

        mainModules.forEach(function (module) {
            var obj = Object.assign({}, request, {
                path: request.path + '/' + module
            });

            resolver.doResolve('file', obj, "file used: " + module, callback);
        });
    });
```

The problem is that only the first file is being included and others ignored. Is this behaviour possible with enhanced-resolver plugin? Any ideas or example would be welcome. @sokra

**Comment by mikesherov** [comment]
Thanks again for contributing, and for building out bower support. It's not really the intention of enhanced-resolve to resolve multiple files, same as `require.resolve`. A fully functioning bower plugin needs to happen at a higher level than the resolver unfortunately. Closing this issue for now. Let me know if you'd like to discuss further.
