### ISSUE TITLE
Incompatibility with node fs api.

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/enhanced-resolve#89]
I'm not sure this is bugs or expected behavior.
Example: `fileSystem.readFileSync(filename, "utf8")`, not respect `utf8` and always return `Buffer`.

**Comment by TheLarkInn** [comment]
What version of node did you see this?

**Comment by evilebottnawi** [comment]
@TheLarkInn i see function as in `fs` module (`readFileSync` and etc), It would be nice to have compatibility them with nodejs `fs`.
Original issue: https://github.com/babel/babel-loader/pull/460 , maybe give more information.

**Comment by mhink** [comment]
@TheLarkInn I ran into this as well. (For reference, the error I was seeing is the same as this one in CopyWebpackPlugin: https://github.com/webpack-contrib/copy-webpack-plugin/issues/217)

The incompatibility is in this method call (and others like it)

https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js#L238

The method signature here is `readFile(path, callback)`, but Node's `fs` methods have the signature `readFile(path, options, callback)` as documented in the following:

https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_readfile_path_options_callback

So if you're doing something like `fs.readFile(pathToMyFile, "utf8", callback)`, CachedInputFileSystem tries to invoke `"utf8"` as a callback, and throws:

`TypeError: callbacks[i] is not a function`

**Comment by rjgotten** [comment]
Hitting this as well in the context of writing a loader for Webpack.

Really annoying and makes it awfully tempting to sidestep the formally correct `this.fs` and just directly hit the raw Node.js internal `fs` module instead.

**Comment by evilebottnawi** [comment]
Fixed before, improved here https://github.com/webpack/enhanced-resolve/pull/254
