### ISSUE TITLE
Error when using webpack in watch mode

### ISSUE THREAD

**Issue by danrot** [webpack/enhanced-resolve#97]
I have updated to the latest release of this library (3.4.0), and that caused the `watch` script I've added to `package.json` (actually it is just `webpack -d -w`) to break. It breaks with this error message:

```
/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145
			if(key.startsWith(what))
			      ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at Watchpack.watcher.once (/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Watchpack.emit (events.js:213:7)
    at Watchpack._onTimeout (/Users/daniel.rotter/Development/massiveart/sulu-minimal/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `webpack -d -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The initial build works, but this error occurs after I save a file being watched. Is there some compatability issue with this release?

If I downgrade to version 3.3.0 of this library the watch task is working again.

**Comment by smares** [comment]
Just wanted to report the same issue.

**Comment by peteringram0** [comment]
Also getting this issue.

**Comment by daohoangson** [comment]
Looks like we have an `undefined` key here, likely from commit 03ef8f2:

```javascript
		for(var key of this.data.keys()) {
			if(key.startsWith(what))
				this.data.delete(key);
		}
```

In a rush so I had to edit it like below as a temporary workaround:

```javascript
		for(var key of this.data.keys()) {
			if (typeof key !== "string") {
				continue;
			}
			if(key.startsWith(what))
				this.data.delete(key);
		}
```

Hope this can be fixed soon.

**Comment by suyi91** [comment]
Getting the same problem using version 3.4.0

**Comment by antonnyman** [comment]
+1

**Comment by MadMikeyB** [comment]
+1

**Comment by Alvin-Liu** [comment]
+1

**Comment by timbergus** [comment]
Same error here.

    webpack: Compiling...
    /Users/Gustavo/Desktop/canvas-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145

                        if(key.startsWith(what))
                              ^
    TypeError: Cannot read property 'startsWith' of undefined

**Comment by the-architect** [comment]
Same issue, had to downgrade again. 
Seems to work in 3.2.0.

**Comment by smares** [comment]
It even works in 3.3.0 @the-architect

**Comment by timobehrens** [comment]
+1

**Comment by gijsjanr** [comment]
+1

**Comment by the-architect** [comment]
@smares yeah sorry, yarn was still installing 3.4.0.

**Comment by jeremyxgo** [comment]
Just facing the same error in 3.3.0
My script: `cross-env NODE_ENV=development webpack-dev-server -d --inline --hot`
When I edit my code and trigger the hot reload, the error shows and break the dev server

**Comment by bongofury** [comment]
+1

**Comment by Kumarsammy** [comment]
+1

**Comment by tomasztomys** [comment]
+1

**Comment by dariuszpaluch** [comment]
+1

**Comment by 3jwddgm** [comment]
+1

**Comment by diegoprd** [comment]
+1

**Comment by danbruegge** [comment]
I tried downgrade to v3.3.0 and v3.2.0 with no success. I had to revert my upgrade from webpack-dev-server v2.6.1 back to v2.5.1. Now it is working again.

**Comment by antonnyman** [comment]
@daohoangson's fix works for me right now

**Comment by emaincourt** [comment]
Downgrading worked for me. If you're using *Yarn*, think about editing your `yarn.lock` file when you install 3.3.0 manually :
```
enhanced-resolve@^3.3.0:
  version "3.3.0"
  resolved "https://registry.yarnpkg.com/enhanced-resolve/-/enhanced-resolve-3.3.0.tgz#950964ecc7f0332a42321b673b38dc8ff15535b3"
  dependencies:
    graceful-fs "^4.1.2"
    memory-fs "^0.4.0"
    object-assign "^4.0.1"
    tapable "^0.2.5"
```

**Comment by the-architect** [comment]
adding `"enhanced-resolve": "3.3.0"` to your package.json dependencies and running yarn is not enough? I can't try it out, because I deleted the yarn.lock file before.

**Comment by Alex-Sokolov** [comment]
Fixed in https://github.com/webpack/enhanced-resolve/releases/tag/v3.4.1

**Comment by emaincourt** [comment]
@the-architect No since webpack expects "enhanced-resolve": "^3.3.0" so Yarn will resolve two different packages since patterns are different when you install it. You need to explicitly link them

**Comment by the-architect** [comment]
@emaincourt that's weird, but ok. thank you. :)

**Comment by danrot** [comment]
Works for me, thanks for fixing!

**Comment by tomasztomys** [comment]
why do you close it?!

**Comment by danrot** [comment]
@tomasztomys Because of that comment: https://github.com/webpack/enhanced-resolve/issues/97#issuecomment-317410074

There is a new release which is fixing this issue.
